### ISSUE TITLE
Temperatur Raumthermostat einstellen - Error 422

### ISSUE THREAD

**Issue by florianze** [DrozmotiX/ioBroker.tado#149]
Hi,

ich wollte über den tado Adapter gerne die Temperatur meines Raumthermostats einstellen - ich verwende keine Heizkörperthermostate von Tado sondern nutze nur das Raumthermo um eine etwas ältere Therme zu steuern. 

In den Objekte in iob habe ich an folgender Stelle versucht die Temperatur zu ändern, um den Datenpunkt vor Erstellung eines blockly zu testen: 

![image](https://user-images.githubusercontent.com/46788414/104426874-d3a75380-5582-11eb-9fdf-b9e54af25a9b.png)

Allerdings erhalte ich dann folgenden Fehler im Log: 

tado.0 | 2021-01-13 09:33:13.644 | error | (28472) Issue at state change : Error: Request failed with status code 422

Ist diese value überhaupt veränderbar? Falls nein, wie kann ich die Temperatur anpassen? Es soll quasi das API pendant zu dieser Einstellung der App sein: 

![1610527085585](https://user-images.githubusercontent.com/46788414/104427069-1701c200-5583-11eb-8ed2-73acac4e4057.JPEG)

Ich habe per npm install den Adapter installiert - die Verbindung der Instanz ist nach dem Login grün.

Vielen Dank vorab!

**Comment by HGlab01** [comment]
Hallo, ja ist veränderbar und funktioniert (eigentlich) auch.
Versuch mal das Objekt direkt zu ändern und nicht über blocky und trage einen Wert ein mit max. einer Nachkommastelle

Wenn das auch nicht geht, dann folge bitte den Schritten in
https://github.com/iobroker-community-adapters/ioBroker.tado/issues/146#issuecomment-757654697

**Comment by florianze** [comment]
Mit der 0.0.20 funktionierte das einstellen der Temperatur wie erwartet, bei folgendem Log-Output: 

`
2021-01-13 12:50:06.029 - info: tado.0 (4161) GETS INTERESSTING!!!
--
2021-01-13 12:50:06.031 - info: tado.0 (4161) Temperature changed for room : 1 in home : 295422 to API with : 18
2021-01-13 12:50:06.959 - info: tado.0 (4161) API called with {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":18}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
`

Kann ich irgendwas bereitstellen, um festzustellen, warum es mit der anderen Version nicht klappt?

**Comment by HGlab01** [comment]
Hallo,
dann nimm dir einfach die Version
https://github.com/HGlab01/ioBroker.tado/archive/v0.0.21.tar.gz
Da sind die Logs wieder reduziert.
Der Fix sollte per Pull-Request in die "normale" Version kommen

@DutchmanNL: noch ein Grund für PR #117 ;-)

**Comment by DutchmanNL** [comment]
> @DutchmanNL: noch ein Grund für PR #117 ;-)

jup :) please teste the merge :)

**Comment by mikekaldig** [comment]
Hey, ich habe mit die 0.26 heute installiert. Doch leider wird der Datenpunkt "Temperatur" nicht erzeugt. Diesen benötige ich ja um manuell die Temperatur zu setzen, oder habe ich einen Gedankenfehler?

![tado](https://user-images.githubusercontent.com/42111533/111833508-90ef5800-88f2-11eb-9dad-e1d8bb8491d2.PNG)

Und hier schon einmal vielen Dank für euren Adapter!

**Comment by DutchmanNL** [comment]
Ich habe heute alle Updates vereint, warte noch auf Feedback und werde Dan 0.2.6 zum Testen freigeben

**Comment by HGlab01** [comment]
Merged version generates warnings (which did not happen in the forked version):
State "tado.0.xxxxxx.Rooms.2.overlayType" has no existing object, this might lead to an error in future versions

I have to check why no object exists for this but StateChanges are performed

**Comment by HGlab01** [comment]
will be fixex in #184

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.2.6
