### ISSUE TITLE
implement child lock

### ISSUE THREAD

**Issue by senger1985** [DrozmotiX/ioBroker.tado#163]
childLockEnabled is now available in the tado application on smartphones
[https://github.com/iobroker-community-adapters/ioBroker.tado/issues/128](url)
[https://forum.iobroker.net/topic/25723/test-adaper-tado-v0-1-x/730](url)

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.2.5
