### ISSUE TITLE
(1505) Send this info to developer !!! { Unhandable information found in DoHome : "quickActionsEnabled" with value : false

### ISSUE THREAD

**Issue by Grothesk242** [DrozmotiX/ioBroker.tado#164]
Log File is bein flooded with this message: 

(1505) Send this info to developer !!! { Unhandable information found in DoHome : "quickActionsEnabled" with value : false

**Versions:**  
 - Adapter version: 0.2.5
 - JS-Controller version: 3.2.16
 - Node version: v14.15.5
 - Operating system: Raspberry OS 'Buster'

**Comment by senger1985** [comment]
These should be these functions @DutchmanNL 
[https://forum.iobroker.net/topic/25723/test-adaper-tado-v0-1-x/727](url)

**Comment by Grothesk242** [comment]
> These should be these functions @DutchmanNL
> [https://forum.iobroker.net/topic/25723/test-adaper-tado-v0-1-x/727](url)

I think this not the child lock but the 'Master' setting that popped up recently in some versions of the app.

**Comment by senger1985** [comment]
> > These should be these functions @DutchmanNL
> > [https://forum.iobroker.net/topic/25723/test-adaper-tado-v0-1-x/727](url)
> 
> I think this not the child lock but the 'Master' setting that popped up recently in some versions of the app.

The post in the forum does not show the child lock mode but the master function of boosting all thermostats or switching them off.
The child lock mode/function is shown in post 730. ;-)

**Comment by nemodil** [comment]
Same log entry for me :

(8180) State "tado.0.388261.Rooms.1.overlayType" has no existing object, this might lead to an error in future versions
(8180) Send this info to developer !!! { Unhandable information found in DoHome : "quickActionsEnabled" with value : false

**Comment by Doreinie** [comment]
Hello
same "warn" message for me: 
Send this info to developer !!! { Unhandable information found in DoHome : "quickActionsEnabled" with value : false

**Comment by HGlab01** [comment]
Should be solved in
https://github.com/HGlab01/ioBroker.tado/archive/v0.2.6-1.tar.gz
You can install the version by using the cat ![image](https://user-images.githubusercontent.com/54232526/108466616-3081e200-7284-11eb-8f9b-6ab3d8ffef5d.png) in the adapter tab.
Let me know if it works for the pull request.

**Comment by smartiebs** [comment]
Thanks @HGlab01 for your work. I my case i looks pretty good after install v0.2.6-2. I will check it later again. If there are any warnings i will inform you about it

**Comment by Doreinie** [comment]
hi, I tried to install from Git but got this error message. Maybe I´m doing something wrong?
any  hints?

$ ./iobroker url "https://github.com/HGlab01/ioBroker.tado/archive/v0.2.6-2.tar.gz"
install HGlab01/ioBroker.tado#v0.2.6-2.tar
NPM version: 7.5.4
npm install HGlab01/ioBroker.tado#v0.2.6-2.tar --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/HGlab01/ioBroker.tado.gitnpm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-02-19T13_17_51_330Z-debug.log
ERROR: host.raspberrypi Cannot install HGlab01/ioBroker.tado#v0.2.6-2.tar: 128
ERROR: process exited with code 25

**Comment by Grothesk242** [comment]
> NPM version: 7.5.4

npm@7 is not recommended for use with ioBroker. Go back to npm6.

**Comment by HGlab01** [comment]
this is somehow a raspberrypi issue. No idea why, but this happens if using a tar.gz file from the github archive.
I you copy the tar.gz to you local file it also raises an error but is installed afterwards.

**Comment by Doreinie** [comment]
Yes, I thought as well that I would get trouble with npm7 but realized that I had less error messages when testing around. 
Hence, I decided to transition to npm7 and hope all will work out. So far so good I can clearly say.
I will try the local file installation...

**Comment by nemodil** [comment]
Hi,
I tried to install Version v0.2.6-2, and got the following error message:
Running the command npm fund doesn't get any information.

My versions are: 
Node.js v12.20.1
npm 6.14.10
js-controller 3.2.7

Any suggestions to resolve that error?

$ ./iobroker url "https://github.com/HGlab01/ioBroker.tado/archive/v0.2.6-2.tar.gz" --debug
install https://github.com/HGlab01/ioBroker.tado/archive/v0.2.6-2.tar.gz
NPM version: 6.14.10
npm install https://github.com/HGlab01/ioBroker.tado/archive/v0.2.6-2.tar.gz --loglevel error --prefix "/opt/iobroker" (System call)
+ iobroker.tado@0.2.6-2
added 14 packages from 9 contributors in 55.582s

61 packages are looking for funding  run `npm fund` for details
ERROR: host.home Cannot install https://github.com/HGlab01/ioBroker.tado/archive/v0.2.6-2.tar.gz: 0
ERROR: process exited with code 25

**Comment by nemodil** [comment]
I installed both versions 0.2.6-2 and 0.2.5, an now i have the following warning every 30 seconds

(29304) State "tado.0.388261.Rooms.1.overlayType" has no existing object, this might lead to an error in future versions

**Comment by HGlab01** [comment]
> I installed both versions 0.2.6-2 and 0.2.5, an now i have the following warning every 30 seconds
> 
> (29304) State "tado.0.388261.Rooms.1.overlayType" has no existing object, this might lead to an error in future versions

which JS-controller version is in use? I guess with js-controller v3.1.6 it does not appear?
You can try to delete this state manually, so that it is created again by the adapter

**Comment by nemodil** [comment]
I use js-controller 3.2.7
After creating the state “tado.0.388261.Rooms.1.overlayType” manually, I have no warnings anymore.
So far the Tado adapter works fine :-)

**Comment by ami-smart** [comment]
> I use js-controller 3.2.7
> After creating the state “tado.0.388261.Rooms.1.overlayType” manually, I have no warnings anymore.
> So far the Tado adapter works fine :-)

Good idea. Did the same.

While checking I saw that not all of my Tado's had this missing state.
3 of 6 had the overlayType by default. After creating the missing the error went away.

**Comment by HGlab01** [comment]
I learned that with the new js-controller it works by using
https://github.com/HGlab01/ioBroker.tado#0.2.6-2

You can install the version by using the cat ![image](https://user-images.githubusercontent.com/54232526/108466616-3081e200-7284-11eb-8f9b-6ab3d8ffef5d.png) in the adapter tab.
Let me know if it works for the pull request.

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.2.6
