### ISSUE TITLE
Send this info to developer !!! { Unhandable information found in DoReadDevices : "childLockEnabled" with value : false

### ISSUE THREAD

**Issue by Thorn2910** [DrozmotiX/ioBroker.tado#168]
With the latest update of the Tado Controller - Tado added a Child Lock possibility

THis is what causes the warnings

Send this info to developer !!! { Unhandable information found in DoReadDevices : "childLockEnabled" with value : false

**Comment by HGlab01** [comment]
Double entry to #129 and fixed in v0.2.5
Using the issue template and mentioning things like used version would help enormously to manage the issues.

**Comment by DutchmanNL** [comment]
thank you @HGlab01
