### ISSUE TITLE
Send this info to developer !!! { Unhandable information found in DoHome : "quickActionsEnabled" with value : false

### ISSUE THREAD

**Issue by RangeMethod** [DrozmotiX/ioBroker.tado#176]
Adapter Version is 0.2.5

**Comment by HGlab01** [comment]
Double entry to #164 

Please check
https://github.com/iobroker-community-adapters/ioBroker.tado/issues/164#issuecomment-781861535

**Comment by DutchmanNL** [comment]
close duplicate
