### ISSUE TITLE
Warning: State "tado.0.xxxxxx.Rooms.x.overlayType" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by HGlab01** [DrozmotiX/ioBroker.tado#184]
**Describe the bug**  
Warning: State "tado.0.xxxxxx.Rooms.x.overlayType" has no existing object, this might lead to an error in future versions
as long as this state was in JSON never != NULL
Therefore especially an issue after new installation since js-controller v3.2.16

**To Reproduce**  
to be fixed at
https://github.com/DrozmotiX/ioBroker.tado/blob/a71a9752c099d4539a70fbd2b2756ed905bc5631/main.js#L1543

**Comment by HGlab01** [comment]
fixed in v0.2.6 with https://github.com/DrozmotiX/ioBroker.tado/commit/e8cccab8a1d906b991ed7d59c180398763ca63b6

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.2.6
