### ISSUE TITLE
Updates werden nicht angezeigt

### ISSUE THREAD

**Issue by Trrw** [DrozmotiX/ioBroker.tado#196]
Ich habe den wunderbaren Adapter per Github installiert über ioBroker. Nun ist mir aufgefallen, dass ich Errors im Log habe. Daher habe ich jetzt gesehen, das es bereits weitere neue Versionen gibt. Ich bin aktuell auf 0.2.2

Leider kann ich den Adapter nicht updaten über Biobroker. Wenn ich nochmal aus der Quelle Github hinzufüge erscheint bei mir auch kein update. Was kann ich tun?

**Comment by DutchmanNL** [comment]
probier mal bitte 

<img width="992" alt="Schermafbeelding 2021-03-31 om 22 53 48" src="https://user-images.githubusercontent.com/7318445/113209947-f7ba2d00-9273-11eb-843c-24b561c9f61b.png">


und dan die URL https://github.com/DrozmotiX/ioBroker.tado.git
