### ISSUE TITLE
Master Switch - Alle Thermostate ausschalten

### ISSUE THREAD

**Issue by SoerenKaiser99** [DrozmotiX/ioBroker.tado#2]
Ein Masterswitch wäre super:

Alle Thermostate gleichzeitig Ein oder Aus Stellen 

evtl auch mit Sommer Modus -> Nur ein wenn Temp unter einstellbaren Wert der Aussentemperatur bei Wetter

**Comment by DutchmanNL** [comment]
baue ich ein sobald die basis Sachen Fertigung stabiel sind.
Im admin kommt dan unter dem haus 1 werte den man auf on/off setzt und dieser geht zu allen Thermostaten


> evtl auch mit Sommer Modus -> Nur ein wenn Temp unter einstellbaren Wert der Aussentemperatur bei Wetter

mja das gehört eigentlich in ein script, oder wir sagen das man im Tado Adapter einige basis Einstellungen vornehmen kan welcher der adapter dan beruecksichttigt.

in der basis mache ich erstmal den Datenpunkt, der muss dan ausserhalb des adapter geschaltet werden aber wird durch den adapter zu allen Thermostaten verarbeitet

**Comment by mitzwein** [comment]
Hi @DutchmanNL. Gibt es hier schon news. Ich bin begeistert von dem Tado-Adapter und der Master-Switch wär ein echtes Premium-Feature!
Danke.

**Comment by DutchmanNL** [comment]
> Hi @DutchmanNL. Gibt es hier schon news. Ich bin begeistert von dem Tado-Adapter und der Master-Switch wär ein echtes Premium-Feature!
> Danke.

sorry hatte ne lange Auszeit, es geht weiter :)

**Comment by HGlab01** [comment]
Simple Antwort: weil dies ein OpenSource Projekt ist und die Leute die an den Adaptern arbeiten in der Regel einen Job und ein Privatleben haben.
Nevertheless... 
In der Alpha ist es mal drinnen
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.11-alpha.0

**Comment by HGlab01** [comment]
The "real" master switch
tado.[x].[yyyyyy].Home.masterswitch
is available in
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.11-alpha.4

**Comment by HGlab01** [comment]
Masterswitch implemented in 0.3.11
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.11
