### ISSUE TITLE
No Actual Temperature and Actual Humidity Value Present

### ISSUE THREAD

**Issue by RangeMethod** [DrozmotiX/ioBroker.tado#212]
There is no Value under Objects for Actual Temperatue and Actual Humidity, it shows (NULL)

  
1. Go to 'Objects/Tado/0/xxxxxxx/Rooms/xx
2. Click on ActualTemperature
3. See Error under Value

I expect a Value of %(Humidity) or Celsius(Temperature)

![image](https://user-images.githubusercontent.com/25565335/116313834-96bc4100-a7ae-11eb-91cc-90882cfb5783.png)

 - Adapter version: 0.2.6
 - JS-Controller version: 3.2.16
 - Node version: 10.16.2
 - Operating system: Ubuntu 20.04.02 LTS

**Comment by HGlab01** [comment]
Hi! What about the log? Are there any entries?
I guess you are using the adapter the first time and it never worked before?
If the log does not show any error please start the adapter in debug mode and attach the log. Thanx!

**Comment by RangeMethod** [comment]
Thanks you very much, 
I turned debugging on and it started working.
nothing was changes from my side, only the logging level.

**Comment by HGlab01** [comment]
I guess it was the restart by changing the log level. You should be able to switch it back to info
