### ISSUE TITLE
Please also add your adapter to the stable repository once ready

### ISSUE THREAD

**Issue by ioBrokerChecker** [DrozmotiX/ioBroker.tado#22]
Your adapter is already in ioBroker latest repository available to be used by testwilling users. In order to make your adapter also available for the wide user base which uses the stable repository you should also add your adapter to the stable repository. Please see instructions at https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-stable-repository

Thank you for your support.

**Comment by DutchmanNL** [comment]
stable release to be expect in September

**Comment by DutchmanNL** [comment]
0.2.0 (stable release candidate) will be released today, after successfully testing next week release to stable

**Comment by simonkurka** [comment]
The stable release didn't connect at my place.

`Disconnected from Tado cloud service ..., retry in 30 seconds !
This will be refused in future versions. Please report this to the developer.
The id "REDACTED" has an invalid type!: Expected "string" or "object", received "number".
Connected to Tado cloud, initialyzing ...`

0.2.4 connected instantly and seems to work as expected.

**Comment by DutchmanNL** [comment]
we expect to release 0.2.6 to stable within the next 2 weeks after all testing is positive

**Comment by DutchmanNL** [comment]
will be released soon after fixing https://github.com/DrozmotiX/ioBroker.tado/issues/44

**Comment by ldittmar81** [comment]
Some news about the stable release?

**Comment by HGlab01** [comment]
Stable version v0.3.3 launched
