### ISSUE TITLE
warning message: `Unhandable information found in DoHome: "enabledFeatures" with value: []`

### ISSUE THREAD

**Issue by sly-1** [DrozmotiX/ioBroker.tado#226]
**Description**  
Since last night I get the following warning message in the log:
`Send this info to developer !!! { Unhandable information found in DoHome: "enabledFeatures" with value: []`

Has something been changed here on tado side and therefore an adaptation in the adapter is necessary?

**To Reproduce**  
1. Go to 'Log'
2. See the tado messages (warn)

**Expected behavior**  
Log entries should no longer appear.

**Versions:**  
 - Adapter version: 0.2.6-2
 - JS-Controller version: 3.2.13
 - Node version: v12.20.1
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Additional context**  
-/-

**Comment by HGlab01** [comment]
If you like you can install and test this one:
DrozmotiX/ioBroker.tado#24e735347d19319bb8fe6a66d552e747deb11fc7

**Comment by sly-1** [comment]
Just installed it over the 'cat'. 
Unfortunately the same log entries are still generated.

**Comment by HGlab01** [comment]
yes, I did a mistake. Sorry. Next try:
DrozmotiX/ioBroker.tado#667940406d1fcc92477252a726a2cdfde5f6e6a5

**Comment by HGlab01** [comment]
> Just installed it over the 'cat'.
> Unfortunately the same log entries are still generated.

yes, I did a mistake. Sorry. Next try:
DrozmotiX/ioBroker.tado#667940406d1fcc92477252a726a2cdfde5f6e6a5

**Comment by sly-1** [comment]
You are my man 😊
That's it, the warnings are gone now. 
Thank you very much for the very fast help. 
What was it? I hope everything else works in this new version. 😉

Will this become an official version? 
How to proceed now, should I continue to use this version? 
When will there be a new 'stable' version?

**Comment by HGlab01** [comment]
Hi, the Tado-API changed.
This version should be even more stable as the "stable" one and yes it will become a public version in the next days or maybe one to two weeks.
There a couple of things to improve so that it works smooth with the next js-controller version.

Will be published with v0.2.7

**Comment by HGlab01** [comment]
I keep it open until the version is launched

**Comment by Grothesk242** [comment]
Party pooper! 
I can't confirm. 
iobroker.tado@0.2.6 (github:DrozmotiX/ioBroker.tado#f5eac08585fa4dc7f41b529b547c0ab5c587a2eb)
still throws 
```
warn: tado.0 (19680) Send this info to developer !!! { Unhandable information found in DoHome: "enabledFeatures" with value: [] 
```

**Comment by HGlab01** [comment]
fixed in
DrozmotiX/ioBroker.tado#2b779523b18e6c63d2d1cb9d2dbabcf18e48f012
and
DrozmotiX/ioBroker.tado#f5eac08585fa4dc7f41b529b547c0ab5c587a2eb
is older
