### ISSUE TITLE
Tado warning enabledFeatures empty

### ISSUE THREAD

**Issue by ldittmar81** [DrozmotiX/ioBroker.tado#234]
Ich habe mir einem Account für Tado erstellt, aber besitze noch keine Geräte (kommen nächste Woche) - ioBroker bringt jetzt alle 30 Sekunden folgende Meldung:

Send this info to developer!!! { Unhandable information found in DoHome: "enabledFeatures" with value: []

Ich denke mal, dass die Meldung automatisch verschwinden wird, sobald ich neue Geräte hinzufüge.

**Versions:**  
 - Adapter version: 0.2.6
 - JS-Controller version: 3.2.16
 - Node version:  12.22.1
 - Operating system: linux

**Comment by sly-1** [comment]
Schau mal hier: https://github.com/DrozmotiX/ioBroker.tado/issues/226#issue-877455208

**Comment by HGlab01** [comment]
fixed in v0.2.7 (474dfc5)
