### ISSUE TITLE
Fenster offen abfragen

### ISSUE THREAD

**Issue by matze19999** [DrozmotiX/ioBroker.tado#237]
Ist es möglich die den Fenster-Offen Status abzufragen?
Aktuell wird ja nur abgefragt, ob die Erkennung aktiviert ist.

Danke! ☺️

**Comment by HGlab01** [comment]
This feature exists. States will be created as soon as the window will be opened for the first time.
tado.0.xxxxxx.Rooms.y.openWindow
![image](https://user-images.githubusercontent.com/54232526/118242935-27c53480-b49e-11eb-8e8e-e4ca47eebb6b.png)
