### ISSUE TITLE
(9429) Send this info to developer !!! { Unhandable information...

### ISSUE THREAD

**Issue by Tripartius** [DrozmotiX/ioBroker.tado#243]
Hey,
I am a Newbie, so please be patient! :)

Since a few days the tado-adapter leaves the stated error. Before that everthing worked fine. Any suggestions, what my problem is and how to fix it?

"(9429) Send this info to developer !!! { Unhandable information found in DoHome : "enabledFeatures" with value : ["AA_7_DAYS_FREE_TRIAL"]

I am not awere, that I do use a trail version of whats soever...

Thank you for your help!
Tripartius

**Comment by HGlab01** [comment]
would be nice, if you would use the issue template, especially mentioning the used version. I guess you are using a version older than 0.2.7?
This topic was added in 0.2.7
![image](https://user-images.githubusercontent.com/54232526/119263253-9614a000-bbde-11eb-98e9-471a33784983.png)

**Comment by Tripartius** [comment]
Sorry for not using the template! My fault!

Yes, I used 0.2.5, now updated to 0.2.6.
I guess the message will dissapear with the 0.2.7 version, correct?

Thank you very much for the promt help!!

**Comment by HGlab01** [comment]
Yes, as I mentioned, was added in v0.2.7
