### ISSUE TITLE
Error: Request failed with status code 422

### ISSUE THREAD

**Issue by GLoBE7823** [DrozmotiX/ioBroker.tado#259]
**Describe the bug**  
Der Adapter startet einwandfrei. Bei der Steuerung meiner Tado AC über ein JS Skript, erhalte ich leider immer nachfolgenden Error. Der Adapter wird dann gekillt und startet neu. Die AC bleibt leider aus. Ich steuere mit JS, nachdem eine Tür geschlossen wurde, zuerst setting.power mit "ON" und 2 Sekunden später overlay.clearZoneOverlay mit "wahr".

`(31814) Request failed with status code 422
error	at processTicksAndRejections (internal/process/task_queues.js:84:21)
error	at endReadableNT (_stream_readable.js:1241:12)
error	at IncomingMessage.EventEmitter.emit (domain.js:483:12)
error	at IncomingMessage.emit (events.js:326:22)
error	at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
error	at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
error	at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
error	(31814) Error: Request failed with status code 422
error	(31814) unhandled promise rejection: Request failed with status code 422
error	(31814) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

Ein ausführlicheres Log findest du im Anhang. Ich hoffe, es ist aussagekräftig (wahrscheinlich ist es viel zu viel :D). Falls was fehlen sollte, gib gerne durch was ich machen und liefern soll.

**Versions:**  
 - Adapter version: 0.3.0-4
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0

**Comment by HGlab01** [comment]
Zuerst mal danke fürs Issue und zu viel Log kann es nie sein ;-)
Ich finde nur kein Attachment zu dem Issue...
Bitte kontrollier im Log, ob es einen Teil gibt mit "GETS INTERESSTING!!!"  Ab da wird es interessant ;-)

**Comment by GLoBE7823** [comment]
Sorry! Ich hoffe, jetzt klappts:

[log-tado.txt](https://github.com/DrozmotiX/ioBroker.tado/files/6633402/log-tado.txt)

Haha okay, wenn es erst ab "GETS INTERESSTING!!!" interessant wird, hab ich mal sicher 90% zu viel Log :D Da aber gleich mal eine Frage, wenn ich schon mal mit einem Experten spreche :D Ist es wohl normal, dass da innerhalb von knapp 5 Minuten so viel Tado Aktivität insgesamt ist? Ich habe manchmal das Gefühl, dass da irgendwas nicht ganz stimmt und dieses volle Log bestätigt meinen Verdacht ein wenig.

Danke für deine Hilfe!

**Comment by HGlab01** [comment]
Zum Thema normal: du hast die Request-Time auf 30 Sekunden gestellt, oder? Dann ist es normal, dass alle 30 Sekunden recht viel passiert.

Im Log finde ich einen Eintrag mit
`FanSpeed set: COOL`
FanSpeed kann eigentlich den Wert Cool nicht haben.
Kannst du mal die JS deaktivieren und manuell die AC über den Datenpunkt auf "ON" stellen und mal sehen was passiert

Funktioniert eigentlich der Adapter in der 0.2.7 bei dir?

**Comment by GLoBE7823** [comment]
Es ist nicht normal, dass wenn ich den Button overlay.clearZoneOverlay betätige, so gar nichts passiert, oder?! Weder im Log noch an irgendeinem Objekt ändert sich etwas?

**Comment by HGlab01** [comment]
das Attribut ab 0.3.0 heißt
tado.0.xxxxx.Rooms.y.overlayClearZone

**Comment by GLoBE7823** [comment]
Danke, das muss ich irgendwie überlesen haben.

Okay, das ist dann eigentlich sogar ja schon die Lösung für mein eigentliches Problem. ;) Ich muss ja nicht noch extra "ON" steuern. Das war mir bisher nicht klar. :D 

Aber der Fehler soll ja trotzdem gefixt werden. :) Daher: hab ich dich richtig verstanden, dass ich jetzt nach "Clear Zone Overlay" = true die nachfolgenden Attribute auf die Werte aus dem Fehler-Log ändern soll, damit wir herausfinden welches Attribut falsch geschrieben wird?

tado.0	2021-06-10 20:57:16.187	debug	(12894) Room mode set: MANUAL
tado.0	2021-06-10 20:57:16.187	debug	(12894) Type set: AIR_CONDITIONING
tado.0	2021-06-10 20:57:16.187	debug	(12894) Room power set: ON
tado.0	2021-06-10 20:57:16.187	debug	(12894) Room Temperature set: 20
tado.0	2021-06-10 20:57:16.186	debug	(12894) DurationInSeconds set: 1800
tado.0	2021-06-10 20:57:16.186	debug	(12894) FanSpeed set: COOL
tado.0	2021-06-10 20:57:16.186	debug	(12894) Mode set: COOL

Das habe ich nämlich eben probiert und habe schon Probleme dabei, die verschiedenen Attribute unter den Objekten der AC zu finden. Hast du da evtl. irgendwo ein Mapping griffbereit oder so? Habe den ganzen Baum durchgeschaut und konnte teilweise nichts finden.

Room mode -> ist das das Attribut tado.0.xxx.Rooms.y.tadoMode im Raum? Es lässt sich für mich nicht editieren. Nach Clear Zone Overlay steht in dem Feld "HOME"

Type -> wurde gefunden und hat gepasst!

Room power -> wurde gefunden und hat gepasst!

Room Temperature set: 20 -> Ist das das Attribut tado.0.xxx.Rooms.y.setting.temperature.celsius? Wenn ja: Das hat reproduzierbar zum Fehler geführt! Nach Clear Zone Overlay steht in dem Feld "24"

DurationInSeconds -> konnte ich nicht finden

FanSpeed -> konnte ich nicht finden

Mode -> Ist das das Attribut tado.0.xxx.Rooms.y.setting.mode? Wenn ja: Wert "COOL" hat gepasst.

**Comment by HGlab01** [comment]
Hallo! Hast du zufällig auch einen Discord.com Account? Da wäre das ganze ein wenig einfacher

**Comment by GLoBE7823** [comment]
Hey @HGlab01! Helfe gerne mit! Mit Discord kann ich leider nicht dienen.

**Comment by HGlab01** [comment]
Ich denke wir brauchen mal eine Session um das gemeinsam durchzuspielen um das Problem zu finden.
Schau dir mal https://discord.com/app
Am einfachsten wäre es du legst dir einen Account an und wir starten dort mal eine (chat)session

**Comment by HGlab01** [comment]
Hallo, noch Interesse dem Fehler auf den Grund zu gehen?

**Comment by HGlab01** [comment]
I guess will be fixed with #309
