### ISSUE TITLE
setting temperature equals "null" when turning off all rooms in Tado-App

### ISSUE THREAD

**Issue by seb2010** [DrozmotiX/ioBroker.tado#260]
v0.3.0-3:  when "turn-off all rooms" is selected in the Tado-App, all room temperature setting show "null"
e.g. in tado.0.??????.Rooms.8.setting.temperature.celsius

Is this a bug? I think for better alignement with underlying scripts, a numeric value (e.g. minimum possible or 0) should be better.

**Comment by HGlab01** [comment]
Hi,
it is on purpose.
If the TADO-API sends NULL or just nothing then the adapter sets the value to NULL.
As of my understand, that's what it's for.
