### ISSUE TITLE
Unhandable information found in DoHome

### ISSUE THREAD

**Issue by kevinlieser** [DrozmotiX/ioBroker.tado#271]
Send this info to developer !!! { Unhandable information found in DoHome: "enabledFeatures" with value: []

**Comment by HGlab01** [comment]
please use the template to fill in the important meta info especially used adapter version. Thanks!

**Comment by HGlab01** [comment]
maybe related https://github.com/DrozmotiX/ioBroker.tado/issues/234

**Comment by HGlab01** [comment]
added in v0.2.7; latest version is v0.3.0
Please upgrade to latest
