### ISSUE TITLE
Error in data refresh at step login: Error: Response Error: 400

### ISSUE THREAD

**Issue by Mc-Rust** [DrozmotiX/ioBroker.tado#290]
Hallo, 

ich habe den Tado Adapter in IOBroker installiert, leider läuft er nicht. 
Bekomme immer dieses hier im Log angezeigt.

tado.0 | 2021-07-15 09:14:10.239 | error | (28286) Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2021-07-15 09:14:10.237 | error | (28286) Error in data refresh at step login: Error: Response Error: 400
tado.0 | 2021-07-15 09:13:39.818 | error | (28286) Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2021-07-15 09:13:39.816 | error | (28286) Error in data refresh at step login: Error: Response Error: 400

tado.0 | 2021-07-15 09:13:09.404 | error | (28286) Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2021-07-15 09:13:09.403 | error | (28286) Error in data refresh at step login: Error: Response Error: 400
tado.0 | 2021-07-15 09:13:08.890 | info | (28286) Started with JSON-Explorer version 0.1.0
tado.0 | 2021-07-15 09:13:08.860 | info | (28286) starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.tado, node: v12.22.2, js-controller: 3.2.16
tado.0 | 2021-07-15 09:13:08.846 | info | (28286) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

Habe auch schon alles mehrfach neu gestartet und neu installiert,  leider ohne Erfolg.

Ich hoffe hier kann mir geholfen werden.

**Comment by HGlab01** [comment]
I guess you entered the wrong Username and/or Password in the config of the instance:

![image](https://user-images.githubusercontent.com/54232526/125802760-f521621f-2f90-480b-b30c-94ab7a563585.png)

**Comment by HGlab01** [comment]
I guess it is solved. Feel free to text again if you have further issues

**Comment by Mc-Rust** [comment]
Hello,

thanks for Help. I´m so blind. That was the Problem. I entered the wrong Username.
