### ISSUE TITLE
Suddenly missing actual room temperature and humidity readings

### ISSUE THREAD

**Issue by fd-mm** [DrozmotiX/ioBroker.tado#302]
Great adapter, thanks a lot DutchmanNL for all the work. Unfortunately I noticed that the actual room temperature values and the humidity (actual_temperature and actual_humidity) for all the rooms no longer appear (blank values) in rider "objects" of iobroker. Also scripts referring to those values cannot pick them up. This had worked very reliably for the past year. Most other tado datapoints (e.g. target temperatures or heating power) are still populated correctly. The adapter shows "green" in ioBroker. This initially happened with version 0.3.3 of the tado adapter. A reboot of the Raspi running ioBroker, of the tado internet bridge and an update to version 0.3.4. of the tado adapter did not solve the issue. The actual temperatures remain available in the tado iOS app and in Apple Home. 

tado adapter version: 0.3.3 and 0.3.4.
JS-Controller version: (iobroker -v in SSH): 3.2.16
ioBroker.admin 4.2.1
Node JS: v12.22.1
NPM: 6.14.12
System: Raspi 4 with plenty of free RAM
Tado internet bridge Firmware 87.1

Happy to provide more details/logs etc.

**Comment by fd-mm** [comment]
After further investigation the missing datapoints appear now under folder "sensorDataPoints", so while I need to re-wire my scripts to those datapoints, we can consider the matter closed. It might have been caused by the recent addition of a separate tado wireless sensor in one of the rooms, which also appears to affect the other rooms. Hope this helps others encountering the same issue. Thanks again for this great adapter.

**Comment by HGlab01** [comment]
exactly this is stated in the Readme
https://github.com/DrozmotiX/ioBroker.tado/blob/main/README.md#breaking-changes-in-v03x
