### ISSUE TITLE
read me link in the Tado adapter is wrong

### ISSUE THREAD

**Issue by Mr-Robot-DE** [DrozmotiX/ioBroker.tado#317]
Im ioBroker -> Tado -> Lies mich -> Änderungsprotokoll -> In neuem Tab Öffnen
Link ist falsch, sollte vermutzlich inkl. ..../blob/.... sein. (unterer Link.)

In ioBroker -> Tado -> read me-> Change log -> Open in new tab
Link is wrong, should probably be incl. .... / blob / ..... (lower link.)

https://github.com/DrozmotiX/ioBroker.tado/main/README.md
https://github.com/DrozmotiX/ioBroker.tado/blob/main/README.md

**Comment by HGlab01** [comment]
scheint ein admin4 Problem zu sein; die Config im Adapter stimmt
In Admin5 (geht morgen Freitag auf Stable) tritt das Problem nicht (mehr) auf
