### ISSUE TITLE
Den tado° intelligenten Zeitplan wechseln

### ISSUE THREAD

**Issue by Barabaschka** [DrozmotiX/ioBroker.tado#337]
Hi. Erstmal vielen Dank für deine Arbeit. Ich finde deinen Adapter super toll. Aber mir fehlt trotzdem folgende Funktionalität. Ich würde gerne mit dem Adapter den tado° intelligenten Zeitplan umzuschalten. Dabei meine ich nicht die Zeiten zu ändern, sondern nur die Möglichkeit haben zwischen eingestellten Zeitplänen zu wechseln.
![Screenshot_20210815-194247~2](https://user-images.githubusercontent.com/89088779/129750419-3854236b-9056-4047-9ee8-ff9f203d9a7f.png)

Denn es ist immer nervig, wenn man im Winter paar freie Tage hat und muss für diesen Zeitraum in jedem Zimmer den Zeitplan für einzelne Arbeitstage zu einem durchgehendem (Mo-So) Plan umzuschalten. Und am Ende das alles wieder zurück.😫 Ich würde das gerne automatisieren wollen. Vielen Dank.

**Comment by HGlab01** [comment]
Hallo! Wenn ich es richtig verstehe, dann wünscht du dir ein Feature, dass die Tado-App nicht kann. Korrekt?

**Comment by Barabaschka** [comment]
Doch die tado-App kann das. Das Bild, das ich angehängt habe, ist ein Screenshot aus der App.

**Comment by HGlab01** [comment]
Die Option zwischen den drei Optionen hin und her zu schalten
![image](https://user-images.githubusercontent.com/54232526/129754914-3dd6f6e3-57f5-4546-9a7e-8f3081e17e9c.png)
sind für dich die Zeitpläne?

**Comment by Barabaschka** [comment]
Ja, genau.

**Comment by HGlab01** [comment]
ok, schau ich mir mal an....

**Comment by HGlab01** [comment]
Inputs:
Request URL: https://my.tado.com/api/v2/homes/283178/zones/1/schedule/timetables
Request Method: GET

Request URL: https://my.tado.com/api/v2/homes/283178/zones/1/schedule/activeTimetable
Request Method: PUT
Payload: {"id":1}
kann 0, 1 oder 2 sein

**Comment by HGlab01** [comment]
Feel free to test
DrozmotiX/ioBroker.tado#2af5bfad09c5dce5405df8ce6559f30765ef25af
by switching to expert mode and using the "cat-symbol" in the tab "Adapters"
![image](https://user-images.githubusercontent.com/54232526/129788683-0b219b7a-f8c0-487c-abb4-ac64e86a26b3.png)

**Comment by Barabaschka** [comment]
Geil, so schnell. Funktioniert! 👍🏼

**Comment by HGlab01** [comment]
alles klar, kommt in die Version 0.3.7

**Comment by HGlab01** [comment]
please test
DrozmotiX/ioBroker.tado#v0.3.7-0

**Comment by Barabaschka** [comment]
Ich bin zwar ein Anfänger in ioBroker, aber aus meiner Sicht die gewünschte Option in DrozmotiX/ioBroker.tado#v0.3.7-1 funktioniert gut. Vielen Dank!

**Comment by HGlab01** [comment]
added in v0.3.7  https://github.com/DrozmotiX/ioBroker.tado/commit/96dfce251d828b106ea5e99141f91a901e765349
