### ISSUE TITLE
Rebuild admin interface to support React Layout (Admin 5)

### ISSUE THREAD

**Issue by DutchmanNL** [DrozmotiX/ioBroker.tado#350]

**Comment by HGlab01** [comment]
Hi @DutchmanNL! Please give me a hint what you would like to do here?  ;-)
Things mentioned in https://github.com/DrozmotiX/ioBroker.tado/issues/222 were done...

**Comment by DutchmanNL** [comment]
Hey @HGlab01 
The adapter settings currently use the html Standard which was used in Admin <5, sind's Admin 5 we basically build it in react or JSON config

This issue was intended to migrate the current index_m.html into jsonConfig as easiest way as we only use username, password and polling settings 
(So doing that in react is overkill)

**Comment by DutchmanNL** [comment]
@HGlab01 PR created please have a look and test :) I also changed the Dependabot settings to once a month which should be enough and save our repo from a lot Dependabot commits 👍

**Comment by HGlab01** [comment]
Implemented in 0.3.15-alpha.3 (Thanks @DutchmanNL 😉)
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.15-alpha.3

**Comment by DutchmanNL** [comment]
No thanks to me you are the tado guru 😁🙏 and your work satisfy's a lot user !
Happy to have you onboard
