### ISSUE TITLE
Geänderte State-Namen werden nach Neustart zurückgesetzt

### ISSUE THREAD

**Issue by borisholowka** [DrozmotiX/ioBroker.tado#354]
Beim ändern der State Namen werden diese wieder auf die Originalnamen zurückgesetzt, sobald Iobroker oder der Adapter neu gestartet werden.

Version 0.3.7

**Comment by DutchmanNL** [comment]
Works as designed die werden von Tado übernommen warum und welche Namen wil man ändern ?

**Comment by Apollon77** [comment]
@borisholowka Das ist immer so eine Sache. Wenn der Adapter es erlauben würde das geändert blebt kommen andere User die sagen "Ich habs bei Tado geändert und iobroker zieht es nicht nach ... Also am besten änder den Namen in tado und es wird gesynct

**Comment by borisholowka** [comment]
@Apollon77 ok und wo kann ich das ändern?

**Comment by Apollon77** [comment]
Keinen blassen Schimmer .. Ich habe kein Tado.

Aber @DutchmanNL Ja wenn es bei Tado nicht änderbar ist dann sollte der Name persistiert weren ... bei controller 3.2+ geht das mit extendObject

**Comment by senger1985** [comment]
@borisholowka was genau möchtest du denn ändern?
 Die Thermostat/Raumnamen?
 Dafür gehe ich die Tado-App auf "Einstellungen" -> "Räu,e & Geräte" -> Auf den Raumnamen klicken -> "Raum-Name",

**Comment by borisholowka** [comment]
@senger1985 Die Namen der Datenpunkte. In den Scripts sieht das so aus:
![image](https://user-images.githubusercontent.com/86146555/132116947-50b0fc51-b620-47f7-885c-7d78b1a2ded6.png)

Das ist absolut nichtssagend. athome was oder wer? Genauso mit den Temperaturen, die heissen für alle Räume Temperature Celsius. Der Datenpunkt sollte einen eindeutigen Namen haben.

**Comment by senger1985** [comment]
@DutchmanNL wäre es evtl. möglich, insoweit zu ändert?
z. B.: "[Zimmername].temperature"
@borisholowka in der Zwischenzeit gibt es so ein Baustein, Namens "Kommentar", den findest du unter "System", mit dem kannst du deine Scripte kommentieren, damit du den Überblick behalten kannst und genau weißt, was du da gerade für ein Script erstellt hast.

**Comment by DutchmanNL** [comment]
> @DutchmanNL wäre es evtl. möglich, insoweit zu ändert?


Theoretisch ja, lasst uns bitte warten auf @HGlab01 (er geniest gerade Urlaub) und sein Feedback dazu abwarten. 

@Apollon77 bin ich mir bewusst und Adapter Struktur ist auch genau deswegen so aufgebaut das der Name per extender object aus der api übernommen wird.
Sonst haben wir das Probleme das Namen Änderungen in tado nicht in ioBroker ankommen … as Said „Works as Designed“

jetzt verstehe ich das Problem auch (wegen scripten) das kan man im Namen lösen wie voriger Vorschlag finde das ne gute idee

**Comment by HGlab01** [comment]
Meiner Meinung nach macht das aktuelle Verhalten Sinn und im State steht auch die ID (ID = 1) des Raums wie zB hier
tado.x.yyyyyy.Rooms.**1**.setting.temperature.celsius
Die gesamte Tado-API arbeitet mit dieser ID. Parallel auch noch den Namen in den Pfad zu geben ist eine redundante (nicht technische Information) und würde den ganzen Adapter deutlich weniger generisch machen. Genau diese Generik war das Ziel des Refactorings, sodass die (instabile) Tado-API dynamisch unterstützt wird.

Ich denke nicht, dass man die "Schwächen" von Blockly (keine Kritik an dem coolen Tool!) durch komplexe Adapter-Änderungen aufwiegen sollte.

Für jeden Raum wird der Name (hier Tado Wohnzimmer) auch in den Channel des Raums mitgenommen:
![image](https://user-images.githubusercontent.com/54232526/132981504-272b58f2-e378-44a0-9cc1-01086b16f948.png)

Durch folgendes Vorgehen kann man (im JS) ein gut lesbares Ergebnis erzielen:
```
const TadoWzID = getIdByName('Tado Wohnzimmer');
if (!TadoWzID) { log("TadoWzID konnte nicht gefunden werden", "error") };
const state_WzTadoSetTemp = TadoWzID + '.setting.temperature.celsius';
setState(state_WzTadoSetTemp, 20);

```
Vermutlich kann man das auch in Blockly?

**Comment by HGlab01** [comment]
Wenn es keine gegenteiligen Argumente gibt, schließe ich das Ticket am Donnerstag ;-)
