### ISSUE TITLE
Werte lassen sich nicht ändern!

### ISSUE THREAD

**Issue by EisTee94** [DrozmotiX/ioBroker.tado#362]
Hallo,
immer wenn ich den Heiz-Soll-Wert an meinem Gerät ändern möchte, wird mir follgendes in der Log angezeigt.
Vielleicht kann mir jemand weiterhelfen :( Ich verzweifel und draußen wirds immer kälter :'D 
Bald macht die Frau ärgern...

Log:

<html><body>

tado.0 | 2021-10-01 11:19:11.402 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
tado.0 | 2021-10-01 11:19:11.400 | info | terminating
tado.0 | 2021-10-01 11:19:11.398 | info | cleaned everything up...
tado.0 | 2021-10-01 11:19:11.378 | error | Request failed with status code 422
tado.0 | 2021-10-01 11:19:11.378 | error | Error: Request failed with status code 422     at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)     at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)     at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)     at IncomingMessage.emit (node:events:406:35)     at IncomingMessage.emit (node:domain:470:12)     at endReadableNT (node:internal/streams/readable:1329:12)     at processTicksAndRejections (node:internal/process/task_queues:83:21)
tado.0 | 2021-10-01 11:19:11.371 | error | unhandled promise rejection: Request failed with status code 422
tado.0 | 2021-10-01 11:19:11.371 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
tado.0 | 2021-10-01 11:19:10.450 | info | Call  API 'ZoneOverlay' for home '429746' and zone '4' with body  {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":19}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
tado.0 | 2021-10-01 11:19:10.449 | info | Temperature changed for room '4' in home '429746' to '19'

</body>
</html>

**Comment by HGlab01** [comment]
Hallo, welche Adapter-Version?
Der Inhalt vom Call sieht eigentlich ok aus und sollte keinen Fehler liefern

**Comment by cc2224cody** [comment]
Selbes Problem, selbe Lösung. Code 422, Instanz crashed, Temperatur ändert sich nicht.
Habe zuerst Version 0.3.10 installiert, danach gabs immerhin keine Crashs, aber auch keine Temeraturänderung.
Durch den Tipp mit den Einstellungen hier im Issue habe ich dann in der App in der Ansicht des Raumes (wo sich manuell die Temperatur einstellen lässt) einen 1h-Timer laufen sehen. Nachdem ich diesen auf Infinite geändert habe, klappt die Steuerung über den iobroker-Adapter wieder. Bis man die App öffnet und wieder in diese Ansicht geht, dann stellt sich automatisch wieder ein 1h-Timer für die aktuelle Temperatur ein und der Adapter wirft Code 422.

Es scheint eine automatische Funktion zum Reset der Temperatur auf den Standardwert zu sein. Konnte nirgends eine Möglichkeit zur Deaktivierung in der App finden. Ich frage aber mal beim Support nach. Das Problem war nun mehr als nervig zu finden.

**Comment by HGlab01** [comment]
@cc2224cody 
Du kannst mal versuchen die Version 0.3.11-alpha.0 versuchen. Damit sollten die 422 gelöst sein - hoffentlich!
Falls die Version nicht angeboten wird, dann kannst direkt mit der URL
https://github.com/DrozmotiX/ioBroker.tado/
die Version installieren.

**Comment by HGlab01** [comment]
in der Zwischenzeit gibt es eine alpha.5 mit einigen Optimierungen für das 422er Isssue
https://github.com/DrozmotiX/ioBroker.tado/archive/refs/tags/v0.3.11-alpha.5.tar.gz

**Comment by HGlab01** [comment]
fixed in 0.3.11
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.11
