### ISSUE TITLE
Änderung im Zeitplan

### ISSUE THREAD

**Issue by tottiMG** [DrozmotiX/ioBroker.tado#363]
Hallo,

mir ist gerade aufgefallen, wenn ich in der Tado-App (Handy) die Temperatur vom nächsten Zeitplan ändere, dann ändert sich nicht nur `tado.0.xxxxxx.Rooms.1.nextScheduleChange.setting.temperature.celsius`
sondern auch `tado.0.xxxxxx.Rooms.1.nextScheduleChange.start`

Ich hatte z.B. die Werte:
Temperatur 20Grad 
Uhrzeit 22 Uhr (bei IOBroker steht **2021-10-01T20:00:00Z**)

Änder ich jetzt im Handy die **Temperatur** auf 22Grad

Dann steht im IOBroker
Temperatur: 20Grad
Uhrzeit: 2021-10-01T22:00:00Z
Es hat sich also die Uhrzeit geändert nicht die Temperatur.

Änder ich dann die Temperatur auf 18 Grad

Dann steht im IOBroker

Temperatur 18Grad
Uhrzeit: 2021-10-01T20:00:00Z

Nun zeigt die Temperatur den Richtigen Wert und auch die Uhrzeit stimmt wieder.

Das Problem mit dem ungewollten ändern der Uhrzeit passiert nur wenn man auf 22Grad einstellt, bei allen anderen Temperaturen ändert sich da nichts.

Es wäre schön, wenn man diese beiden Punkte auch über den IOB anpassen könnte. 

Gruß Torsten

**Comment by HGlab01** [comment]
Hallo, der Tado-Adapter liest hier einfach nur das aus, was der Tado-Server liefert. Es gibt hier keine Interpretation im Adapter.
Du kannst aber mal bitte den Adapter im Debug-Modus starten und dann den Inhalt vom Datenpunkt
tado.x.yyyyyy._JSON_response.Stage_09_ZoneStates_data_z
wobei z der Zone entspricht für die das auftritt.

Damit kann man noch kontrollieren, was der Tado-Server schickt.

**Comment by tottiMG** [comment]
Seltsamer Weise tritt das "Phänomen" nicht mehr auf. Konnte es am Freitag aber mehrfach rekonstruieren!

Meine andere Frage war ja noch ob noch die Möglichkeit kommt den Zeitplan über den IOBroker anzupassen.
`tado.0.xxxxxx.Rooms.1.nextScheduleChange.setting.temperature.celsius` Temperatur
`tado.0.xxxxxx.Rooms.1.nextScheduleChange.start` Startzeitpunkt

**Comment by HGlab01** [comment]
Hallo!
Persönlich glaube ich, dass es ein very nice to have ist, auch über den Adapter den Schedule zu ändern. Schlage vor, du legst dafür ein eigenes Issue an als "Enhancement Request" und vielleicht hat ja jemand Lust das Feature einzubauen und einen PR zu stellen.

Das Ticket mache ich mal unter dem Gesichtspunkt zu.
