### ISSUE TITLE
Tado Adapter verbindet sich nicht mehr

### ISSUE THREAD

**Issue by drpepperDE** [DrozmotiX/ioBroker.tado#391]
Seit ca. 5 Tagen bekomme ich im ioBroker folgende Meldungen wenn ich den Tado Adapter starte

tado.0 | 2021-11-14 08:47:46.333 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
-- | -- | -- | --
tado.0 | 2021-11-14 08:47:46.333 | error | Error in data refresh at step getMet_data: Error: Not yet logged in
tado.0 | 2021-11-14 08:47:46.332 | info | Connected to Tado cloud, initialyzing...
tado.0 | 2021-11-14 08:47:36.281 | info | Started with JSON-Explorer version 0.1.2
tado.0 | 2021-11-14 08:47:36.260 | info | starting. Version 0.3.7 in /opt/iobroker/node_modules/iobroker.tado, node: v12.22.6, js-controller: 3.3.18

Wie kann ich das Problem lösen?

**Comment by HGlab01** [comment]
Username und Password kontrollieren?

**Comment by drpepperDE** [comment]
Das hab ich schon 2 mal neu eingegeben, auch einen zweite Instanz installiert und Benutzernahmen und Passwort neu eingegeben. Leider ohne Erfolg

**Comment by sly-1** [comment]
Kannst Du dich an der tado Website anmelden? 
[https://app.tado.com/#/account/sign-in]

**Comment by drpepperDE** [comment]
ja das klappt

**Comment by HGlab01** [comment]
ich hab es bei mir gerade nochmals ausprobiert. Wenn ich falsche Credentials eintrage kommt genau die Meldung.
In der Version
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.11-alpha.5
--> https://github.com/DrozmotiX/ioBroker.tado/archive/refs/tags/v0.3.11-alpha.5.tar.gz
ist die Meldung noch feingranularer, da sieht man ob es wirklich am Login-Step scheitert.
In Sentry sind dazu keine vermehrten Meldungen zu finden, daher unwahrscheinlich, dass es was mit dem Adapter zu tun hat.
Wurde sonst etwas am iobroker-setup verändert, dass eventuell den sideeffect auslöst?

**Comment by drpepperDE** [comment]
ich hatte nur die Namen der Power Schalter umbenannt über den Stift rechts. Sodass ich Sie im Script besser zuordnen kann. Dies war 5-6 Tage bevor der Fehler aufgetreten ist. Sonst habe ich nichts am ioBroker verändert.
![Bildschirmfoto 2021-11-15 um 10 14 12](https://user-images.githubusercontent.com/72227206/141754727-fb03dcb0-bb4a-4cbb-b272-3b9d242cdf50.png)
 Auch wenn ich die ganzen Umbenennungen rückgängig mache kommt der Fehler noch. Wie kann ich denn auf die Version 0.3.11 aktualisieren? Vielleicht gibt es da mehr Infos im Log

**Comment by HGlab01** [comment]
@drpepperDE 
mitgelöst mit #392?

**Comment by HGlab01** [comment]
ich vermute mal ja.... wenn nicht bitte reopen
