### ISSUE TITLE
Unerwartete Abbrüche der Verbidungen zur Cloud

### ISSUE THREAD

**Issue by EisTee94** [DrozmotiX/ioBroker.tado#392]
Hallo,
nachdem der Adapter im ioBroker eigentlich stabil lief, tauchten plötzlich Probleme auf.
Der Adapter kann sich plötzlich nicht mehr mit der Cloud verbinden, und hinterlässt einige Einträge in der Log (siehe unten).

Es gibt keinen Auslöser für dieses Verhalten. Es passiert ohne äußerliche Einflüsse.
Auch die Retrys funktionieren dann nicht verlässlich.

Der Fehler lässt sich nicht nreproduzieren, sondern taucht plötzlich und unerwartet (immer dann wenn ich nicht da bin) wieder auf.

User und Password hab ich mehrfach neu eingetippt (sogar in Klarschrift reinkopiert) und natürlich mit der Tado-Website getestet.
Diese Daten sind definitiv korrekt. 

Ich freu mich auf hilfe :) 

Log:
<html><body>

tado.0 | 2021-11-15 07:12:31.044 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
-- | -- | -- | --
tado.0 | 2021-11-15 07:12:31.044 | error | Error in data refresh at step DoMobileDevices: Error: connect ETIMEDOUT 54.77.37.248:443
tado.0 | 2021-11-15 07:10:17.596 | info | Connected to Tado cloud, initialyzing...
tado.0 | 2021-11-15 07:09:47.204 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2021-11-15 07:09:47.202 | error | Error in data refresh at step DoZones: Error: connect ETIMEDOUT 52.215.169.194:443
tado.0 | 2021-11-15 07:06:32.712 | info | Initialisation finished, connected to Tado cloud service refreshing every 30 seconds
tado.0 | 2021-11-15 07:06:30.102 | info | Connected to Tado cloud, initialyzing...
tado.0 | 2021-11-15 07:06:29.583 | info | Started with JSON-Explorer version 0.1.2
tado.0 | 2021-11-15 07:06:29.546 | info | starting. Version 0.3.7 in /opt/iobroker/node_modules/iobroker.tado, node: v12.22.7, js-controller: 3.3.18

</body>
</html>

**Versions:**  
 - Adapter version: 0.3.7
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: aktuellste PiOs Headless version

**Comment by HGlab01** [comment]
Hallo,
nachdem du offensichtlich keine neue Version installiert hast (?) und die gleiche Version nun weniger stabil läuft, wird es nicht am Adapter liegen.
Die Fehlermeldungen bedeuten, dass der Adapter den Tado-Server nicht erreichen konnte bzw. der Server nicht geantwortet hat. Ich sehe zwei Möglichkeiten:
1. dein internes Netzwerk hat ein Issue
2. der Tado-Server hatte ein Issue (bei mir gibt es aktuell keine Probleme zum Tado-Server, der scheint stabil zu sein)

Du kannst aber mal die release v0.3.11-alpha.4 ausprobieren, da sind auch ein paar Internet-Checks drinnen bzw. wurden die Fehlermeldungen optimiert.

**Comment by drpepperDE** [comment]
Habe den Fehler gefunden, habe seit ca. 1 Monat PiHole laufen, offensichtlich ist da der Tado-Server in eine Liste gekommen die ich aus dem Netz habe und diese wird von dort aus ständig aktualisiert. Hatte den PiHole schon deaktiviert, aber die DNS Anfragen noch darüber laufen lassen. Jetzt wo ich es im Router geändert habe läuft der Adapter wieder.
Vielen Dank für deine Mühe, ich muss wohl die Listen überarbeiten.
