### ISSUE TITLE
Adapter hat keine Verbindung zum Internet

### ISSUE THREAD

**Issue by flisse** [DrozmotiX/ioBroker.tado#399]
Ich habe wahrscheinlich seit einiger Zeit ein Problem mit dem Adapter.
Wie lange das Problem bereits besteht weiß ich nicht, es fiel mir nur aktuell auf, wo die Heizung wieder mehr genutzt wird.
Der Fehler besteht darin, dass der Adapter scheinbar keine Verbindung zum Internet herstellen kann. Somit bekomme ich keine Werte und kann auch nichts steuern.
In den Logs von ioBroker kommt immer nur diese Meldung:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/56347866/143501323-f2d65ef8-6b27-40cc-999e-ab369acc0623.png">
Ich kann mich auf der Tado-Seite direkt anmelden und dort auch meine Thermostate sehen und steuern, also von der Seite ist alles OK. Ich habe auch bereits meinen Router und auch den Tado Hub neu gestartet.

**Comment by HGlab01** [comment]
Adapter-Version wäre hilfreich...
Der Adapter testet die Internetverbindung durch einen ping an "dns.google". Wenn dieser fehlschlägt und ein zweiter Versuch auch fehlschlägt kommt der Fehler.
Ich gehe daher zu 99,9% davon aus, dass es an deiner Infrastruktur liegt.
Du kannst mal auf dem Server, auf dem iobroker läuft einen Ping ausprobieren. Sollte ca. so aussehen. Die zurückgegebene IP ist normalerweise entweder 8.8.8.8 oder 8.8.4.4

```
ping dns.google

PING dns.google (8.8.8.8) 56(84) bytes of data.
64 bytes from dns.google (8.8.8.8): icmp_seq=1 ttl=116 time=10.5 ms
64 bytes from dns.google (8.8.8.8): icmp_seq=2 ttl=116 time=10.0 ms
64 bytes from dns.google (8.8.8.8): icmp_seq=3 ttl=116 time=10.1 ms
64 bytes from dns.google (8.8.8.8): icmp_seq=4 ttl=116 time=9.86 ms
64 bytes from dns.google (8.8.8.8): icmp_seq=5 ttl=116 time=9.72 ms
```

**Comment by flisse** [comment]
Installiert ist die Version 0.3.12
Mein Iobroker läuft per Proxmox auf einem IntelNUC. 
Den Ping habe ich ausgeführt, die Verbindung klappt:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/56347866/143569203-067b031a-a7fa-4a71-9f5e-94c9ee90cf6b.png">
Habe auch einmal den Terminal Adapter im Iobroker installiert, auch da funktioniert der Ping.
Hier noch Infos von meiner Iobroker Umgebung:
Node.js: v12.21.0
NPM: v6.14.11

**Comment by HGlab01** [comment]
Du kannst mal die Version ausprobieren. Da hab ich den Internet-Check geändert
DrozmotiX/ioBroker.tado#6299fd0ff0a4e79820747cb3b34adcf57ce4f4be
![image](https://user-images.githubusercontent.com/54232526/143571189-3d8d757b-a6f0-4d6d-b52d-41311225ca24.png)

Vielleicht klappt es damit?

**Comment by flisse** [comment]
Sehr geil. Funktioniert wieder. Vielen Dank für den schnellen support.

**Comment by HGlab01** [comment]
all right, dann kommt diese neue Lösung in die 0.3.12

**Comment by HGlab01** [comment]
fixed in 0.3.13
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.13
