### ISSUE TITLE
Klimasteuerung nimmt keine Kommandos an

### ISSUE THREAD

**Issue by Doreinie** [DrozmotiX/ioBroker.tado#403]
Wenn ich bei der Tado Klimaanlagensteuerung die Temperatur über Iobroker ändern möchte (setting.temperature.celsius) crashed der Adapter leider. Das Problem ist einfach zu reproduzieren bei jedem Versuch die Temperatur zu ändern.
Die Daten der Klimasteuerung werden genauso angezeigt wie die Daten der Heizkörperventile.
`<html>
<body>

tado.0 | 2021-11-29 21:18:04.757 | info | Initialisation finished, connected to Tado cloud service refreshing every 30 seconds
-- | -- | -- | --
tado.0 | 2021-11-29 21:18:02.689 | info | Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'horizontalSwing' with value 'OFF' and type of value 'string'
tado.0 | 2021-11-29 21:18:02.686 | info | Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'verticalSwing' with value 'OFF' and type of value 'string'
tado.0 | 2021-11-29 21:18:02.682 | info | Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'fanLevel' with value 'AUTO' and type of value 'string'
tado.0 | 2021-11-29 21:17:57.920 | info | Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'showScheduleSetup' with value 'false' and type of value 'boolean'
tado.0 | 2021-11-29 21:17:56.839 | info | Connected to Tado cloud, initialyzing...
tado.0 | 2021-11-29 21:17:56.278 | info | Started with JSON-Explorer version 0.1.2
tado.0 | 2021-11-29 21:17:56.239 | info | starting. Version 0.3.7 in /opt/iobroker/node_modules/iobroker.tado, node: v14.18.1, js-controller: 3.3.20
tado.0 | 2021-11-29 21:17:21.545 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
tado.0 | 2021-11-29 21:17:21.542 | info | terminating
tado.0 | 2021-11-29 21:17:21.541 | info | cleaned everything up...
tado.0 | 2021-11-29 21:17:21.524 | error | Request failed with status code 422
tado.0 | 2021-11-29 21:17:21.524 | error | Error: Request failed with status code 422 at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11) at IncomingMessage.emit (events.js:412:35) at IncomingMessage.emit (domain.js:475:12) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
tado.0 | 2021-11-29 21:17:21.515 | error | unhandled promise rejection: Request failed with status code 422
tado.0 | 2021-11-29 21:17:21.514 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

Ist da irgendetwas was ich machen kann?

**Comment by HGlab01** [comment]
Da ich selbst keine Tado-AC Steuerung habe ist es mit dem Reproduzieren nicht so einfach.
Bitte mal den aktuellen Adapter installieren. Dort gibt es dann detailliertere Fehlermeldungen. Danke!

**Comment by Doreinie** [comment]
Danke für die schnelle Antwort! 
Jetzt habe ich den Adapter update gemacht aus dem beta mit Version:  0.3.12
Bei der Temp Änderung crashed er nicht mehr. 
Es gibt diese Meldung wenn ich die Temp von 18 auf 19 Grad ändere.
Der IOB nimmt die 19°C für ca 30 Sekunden und schaltet dann wieder zurück auf 18°C.
In der Tado APP wird keine Änderung angezeigt.

`<html>
<body>


tado.0 | 2021-11-29 22:03:13.204 | error | Issue at setZoneOverlay: 'Error: Request failed with status code 422'. Based on config {"setting":{"type":"AIR_CONDITIONING","fanSpeed":"AUTO","mode":"COOL","power":"ON","temperature":{"celsius":19}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
-- | -- | -- | --



</body>
</html>`

**Comment by HGlab01** [comment]
Die wichtige Zeile im Log fehlt. Vermutlich sieht die so aus:
`Error: Request failed with status code 422 with response {"errors":[{"code":"setting.notSupported","title":"fan speed not allowed in mode COOL"}]}`

**Comment by HGlab01** [comment]
Du kannst diese Version mal probieren:
DrozmotiX/ioBroker.tado#2a73ea44bee1b18845997775a239361b63d25758

![image](https://user-images.githubusercontent.com/54232526/143945065-78288946-a4d6-493c-9ed9-b9907eca9c73.png)

**Comment by Doreinie** [comment]
habe ich probiert. 
Die Symptome sind die gleichen wie zuvor. Ich kann den Eintrag ändern. Stellt sich aber wieder selbst zurück.
`<html>
<body>


Issue at setZoneOverlay: 'Error: Request failed with status code 422'. Based on config {"setting":{"type":"AIR_CONDITIONING","mode":"COOL","power":"ON","temperature":{"celsius":19}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
--



</body>
</html>`

**Comment by HGlab01** [comment]
`Body "{"setting":{"type":"AIR_CONDITIONING","mode":"COOL","power":"ON","temperature":{"celsius":19}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}" for API call "/api/v2/homes/xxxxxx/zones/8/overlay"`

`Error: Request failed with status code 422 with response {"errors":[{"code":"setting.notSupported","title":"fan level not in supported fan levels [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, LEVEL5, AUTO]"}]}`

**Comment by HGlab01** [comment]
next try:
DrozmotiX/ioBroker.tado#ea5cf09f69eda6dd025625a4e46fe09c89f61cef

Leider erwartet sich die API abhängig vom Modus unterschiedliche Daten. Neu ist, dass nun auch der fanLevel benötigt wird.
Ich hoffe der ist als Datenpunt unter... setting.fanLevel analog fanSpeed?
Wenn nicht würde ich den Pfad zum "fanLevel" brauchen.

**Comment by Doreinie** [comment]
Hier ein Bild der Struktur in "Objekte". Ist es das was du meinst?

![image](https://user-images.githubusercontent.com/57943613/144005888-156da23f-04b7-4c59-8a96-8d9fdfa34799.png)

**Comment by HGlab01** [comment]
Das hilft!
fanSpeed gibt es gar nicht (mehr)?

**Comment by HGlab01** [comment]
Solltest du Discord haben, dort wäre es einfacher...
HGlab01#5336

**Comment by Rene5555** [comment]
hier das Log vom Versuch, die Klimaanlage einzuschalten:`javascript.1	2021-12-07 08:45:25.100	info	script.js.Tado_Test: Schedule Klima aus
javascript.1	2021-12-07 08:35:25.085	info	script.js.Tado_Test: Schedule Klima ein
javascript.1	2021-12-07 08:35:25.083	warn	at processTimers (internal/timers.js:497:7)
javascript.1	2021-12-07 08:35:25.082	warn	at listOnTimeout (internal/timers.js:554:17)
javascript.1	2021-12-07 08:35:25.080	warn	at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7)
javascript.1	2021-12-07 08:35:25.079	warn	at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28
javascript.1	2021-12-07 08:35:25.078	warn	at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:168:15)
javascript.1	2021-12-07 08:35:25.076	warn	at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1313:34)
javascript.1	2021-12-07 08:35:25.075	warn	at Object.<anonymous> (script.js.Tado_Test:48:5)
javascript.1	2021-12-07 08:35:25.073	warn	at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1439:20)
javascript.1	2021-12-07 08:35:25.064	warn	State "tado.0.817182.Rooms.1.setting.fanLevel" not found
javascript.1	2021-12-07 08:32:11.911	info	script.js.Tado_Test: registered 0 subscriptions and 3 schedules
javascript.1	2021-12-07 08:32:11.693	info	Start javascript script.js.Tado_Test

tado.0	2021-12-07 08:35:26.132	error	Issue at setZoneOverlay: 'Error: Request failed with status code 422'. Based on config {"setting":{"type":"AIR_CONDITIONING","mode":"COOL","verticalSwing":"OFF","horizontalSwing":"OFF","fanLevel":"AUTO","power":"ON","temperature":{"celsius":20}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
tado.0	2021-12-07 08:35:26.120	error	Error: Request failed with status code 422 with response {"errors":[{"code":"setting.notSupported","title":"horizontal swings not allowed in mode COOL"}]}
`

**Comment by Apollon77** [comment]
Try to restart JavaScript Adapter because it seems that the object is no longer known to Javascript ... or check that the object "tado.0.817182.Rooms.1.setting.fanLevel" really exists. This is regarding the Javasscritp errors.

**Comment by Rene5555** [comment]
Ich habe soeben sowohl den JavaScript Adapter als auch den Tado Adapter (jetzt im Debug-Mode) neu gestartet. Der Datenpunkt ""tado.0.817182.Rooms.1.setting.fanLevel" ist da und lässt sich auch beschreiben. Im Log fand ich jetzt den Eintrag
"Error: Request failed with status code 422 with response {"errors":[{"code":"setting.notSupported","title":"horizontal swings not allowed in mode COOL"}]}" und auch "Issue at setZoneOverlay: 'Error: Request failed with status code 422'. Based on config {"setting":{"type":"AIR_CONDITIONING","mode":"COOL","verticalSwing":"OFF","horizontalSwing":"OFF","fanLevel":"LEVEL1","power":"ON","temperature":{"celsius":20}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}" und den Hinweis "debug: State change detected from different source than adapter"

**Comment by HGlab01** [comment]
Wenn ich es richtig verstanden habe, gibt es in der Zwischenzeit zwei Versionen für Tado-AC.
Hast du die "alte" oder die "neue" Version im Einsatz?
GIbt es auch einen Datenpunkt "fanSpeed"?
Wenn du den Adapter neu startest steht dann in fanSpeed oder in fanLevel ein Wert drinnen?

**Comment by Doreinie** [comment]
@HGlab01 
Was wir testeten und jetzt funktionsfähig haben ist die V3+ Version.
Danke für die Hilfe!

**Comment by Rene5555** [comment]
Ich gehe davon aus, dass ich die neue Version (vor einer Woche gekauft) Smart AC Control V3+habe. Beim Neustart und auch wenn die AC aus ist steht 'tado.0.817182.Rooms.1.setting.fanLevel' auf (none). Ebenso wie mode und verticalSwing.

**Comment by Rene5555** [comment]
ich hab jetzt die alpha.4 in Verwendung. COOL, DRY und FAN können jetzt problemlos angesteuert werden. Beim AUTO gibt es noch Fehler:
`11:25:40.089	error	Issue at setZoneOverlay: 'Error: Request failed with status code 422'. Based on config {"setting":{"type":"AIR_CONDITIONING","mode":"AUTO","verticalSwing":"ON","fanLevel":"LEVEL1","power":"ON"},"termination":{"typeSkillBasedApp":"TIMER","durationInSeconds":900}}
11:25:40.087	error	Error: Request failed with status code 422 with response {"errors":[{"code":"setting.notSupported","title":"temperature required for mode AUTO"}]}
`

**Comment by HGlab01** [comment]
Danke! Wie ist es bei DRY? Ich würde vermuten, das DRY keine Temperatur will?

**Comment by Rene5555** [comment]
Doch, DRY lässt Temperaturangabe zu. Was nicht einstellbar ist, ist fanLevel. Ich habs mit diesen Vorgaben getestet: `setState(dp_Klima + 'mode' ,'DRY');
 setState(dp_Klima + 'temperature.celsius',21);
 setState(dp_Klima + 'verticalSwing','OFF');
 setState(dp_Klima + 'power','ON');`

**Comment by HGlab01** [comment]
fixed in 0.3.13
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.13
