### ISSUE TITLE
Tado Adapter stürzt bei Temperaturwerteingabe ab

### ISSUE THREAD

**Issue by tigginho** [DrozmotiX/ioBroker.tado#412]
Hallo DutchmanNL,

habe schon von anderen Issues mit ähnlichem Problem hier gelesen, aber die Lösungen scheinen nicht zu helfen. 
Sobald ich per Script einen Temperaturwert schreibe  (unter rooms/setting/temperature) stürzt der Adapter ab und startet sich mehrfach neu. Seltsamerweise nicht jedes mal, aber mehrmals täglich.

Der Fehler besteht bei mir bei Version 0.3.7 genau so wie unter 0.3.10 , 0.3.11 oder 0.3.13-alpha.4

Bridge ist V3+

Habe zwischenzeitlich auch schon eine Verzögerung von ca. 60 Sekunden pro Wertänderung in meine Scripte gepackt, brachte auch keinen Erfolg.

Übersehe ich etwas ganz dummes? So langsam verzweifle ich hier, da ich auch die Anwesenheitserkennung über Tado laufen lasse und durch das Abstürzen hier regelmäßig Kirmesbeleuchtung in der Wohnung habe :D

Die Screenshots vom Log sind mit V 0.3.10 vor ein paar Minuten entstanden. Der Rest sind meine nicht professionellen Scripte.

liebe Grüße!

![FehlerLog](https://user-images.githubusercontent.com/96883787/147775310-11943fd6-cfe9-445c-8f84-2eb9deeaf7d1.jpg)
![InfoLog](https://user-images.githubusercontent.com/96883787/147775435-d278ec08-a6d8-4c81-af63-bb1e414b1407.jpg)
![AnwesenheitScript](https://user-images.githubusercontent.com/96883787/147775690-9fce0ab5-e04f-4064-afd0-332610d659fd.jpg)
![FensterScript](https://user-images.githubusercontent.com/96883787/147775695-aa8fcf11-5d3a-47db-a7d2-41796bf34802.jpg)

**Comment by sly-1** [comment]
Du könntest mal die Log-Stufe deiner tado Instance auf Debug stellen. 
Dann den Fehler reproduzieren und ein lesbares Log (Textfile attachen oder als "insert code" formatieren) zur Verfügung stellen. 
Denke das hilft bei der Analyse.

**Comment by HGlab01** [comment]
Nimm bitte mal die letzte alpha zur 0.3.13 und paste den log im info mode erneut.
Beim log fehlt eine entscheidende Zeile. Eigentlich ist die schon in 0.3.10 drinnen aber in der letzten alpha sehr sicher

**Comment by tigginho** [comment]
Nachdem es mit der Alpha.9 einen Tag lang funktionierte trat der Fehler heute nachmittag erneut auf. Leider komplett ohne Eintrag im log unter Info, Fehler oder Warnung. Habe den Adapter jetzt auf Debug gestellt und poste das Ergebnis hier sobald es erneut passiert. 
Wünsche ein frohes neues Jahr!

**Comment by HGlab01** [comment]
war es am o1.01.2022 um 16:08?
![image](https://user-images.githubusercontent.com/54232526/147905560-246f8a45-be9a-474d-9f84-f9a0ff374f56.png)

**Comment by tigginho** [comment]
ca. 10 Minuten vorher aber kommt hin. 
Konnte den Fehler grad durch triggern der Anwesenheitsvariable (Anwesenheit false = alle Thermostate 18°C, true = alle Thermostate auf Tempwert aus Datenpunkt) reproduzieren und hab dir den Fehlerlog im Debug Modus angehangen. Im Info/Warn/Error steht leider weiterhin nichts, egal auf welchen log-Mode ich den tado-Adapter schalte.
Hoffe du kannst mit dem Log was anfangen, ich blick da nicht durch, bin aber auch absoluter Laie auf dem Gebiet :-D

Um 11:48:32 fängt er an für alle möglichen Werte (null) einzutragen.

Genutzte Version ist weiterhin die alpha.
[FehlerLog.txt](https://github.com/DrozmotiX/ioBroker.tado/files/7801624/FehlerLog.txt)
9

**Comment by HGlab01** [comment]
Ganz verstehe ich nicht was du gemacht hast.
Du setzt den Wert
tado.0.xxxxx.Home.state.presence
auf false und dann wieder auf true?

```
2022-01-03 11:48:30.978 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '8' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":22}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
2022-01-03 11:48:31.606 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '2' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":22}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
2022-01-03 11:48:32.191 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '6' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":19}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
2022-01-03 11:48:32.883 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '4' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":22}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
2022-01-03 11:48:35.653 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '8' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":18}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
2022-01-03 11:48:36.339 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '2' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":18}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
2022-01-03 11:48:37.044 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '4' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":18}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
2022-01-03 11:48:37.737 - debug: tado.0 (7298) API 'ZoneOverlay' for home 'xxxxxx' and zone '6' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":18}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
```

Im Log sieht man dass du für deine 4 Räume die Temperaturen rauf und runter spielst und der Adapter die Calls so lange buffert bis er alle absetzen kann. Das scheint aber zu gelingen.

Wie macht sich dann der Fehler bemerkbar? Stürzt der Adapter komplett ab?

**Comment by tigginho** [comment]
Nein ich habe im Objektbaum des iobrokers unter Userdata einen Datenpunkt "Anwesenheitserkennung" erzeugt, den ich in einem Script auf true schalte sobald tado eines unserer Handys als anwesend erkennt und false falls keiner da ist. Dazu nehme ich die Variable Mobile_Devices/deviceMetadata/location/atHome aus dem tado-Adapter.

Den Wert tado.0.xxxxx.Home.state.presence ändere ich nicht.

Den Datenpunkt "Anwesenheitserkennung" hab ich dann mehrfach, mit einem gewissen Zeitabstand manuell hin und her geschaltet um mein Heizungsscript zur Anwesenheit so lange zu triggern, bis der Fehler auftritt.

Meistens klappt das ganze auch. Ebenso die Temperaturabsenkung durch meine Fensterkontakte. Wenn der Fehler dann aber auftritt, schaltet der tado adapter so gut wie alle Werte im Objektbaum kurzzeitig auf (null) und nach einigen Sekunden wieder auf die alten Werte. Das ganze wiederholt sich dann ein paar mal, bis er sich wieder "gefangen" hat. Während dieser Zeit läuft die iobroker Oberfläche auch sehr "laggy", scheint dem raspberry einiges abzuverlangen.

Ich konnte leider noch keine Regelmäßigkeit finden, die das ganze auslöst. 
Manchmal klappt es den halben Tag (zwischendurch werden Fenster geöffnet und geschlossen, jemand verlässt den "Home" Bereich, alles in Ordnung). Dann öffne ich in einem Zimmer das Fenster und der Adapter spielt verrückt. Oder jemand von uns kommt nach Hause und das gleiche passiert. Das ganze macht sich dann dadurch bemerkbar, dass das Licht in der ganzen Wohnung mehrfach aus und wieder angeht. Läuft in einem separaten Script auch über den Datenpunkt "Anwesenheitserkennung".

Ich will nicht ausschließen, dass ich irgendwo einen Fehler in meinen Scripten eingebaut habe, deshalb habe ich die beiden für Anwesenheit-Heizung und Fensterkennung ganz oben mit angefügt.

Ich habe mir vorerst damit beholfen in die Anwesenheitserkennung einen timeout zu setzen um dieses hin und her springen zu unterbinden, aber das ist ja nur Symptombekämpfung :-D

**Comment by HGlab01** [comment]
zu deinen eigenen Scripten kann ich schwer was sagen; komisch ist, dass du zuerst die Temp, 22/22/19/22 und 5 Sekunden später auf 18/18/18/18
Macht das Sinn?
Vom Adapter-Log sieht alles sauber aus. Normalerweise fängt der Adapter die Fehler sauber ab.
Wenn nicht wird der Adapter vom ioBroker-Controller neu gestartet - das würdest aber auch im Log erkennen

**Comment by tigginho** [comment]
Das kann gut sein, das entspricht den aktuellen Werten für An-/Abwesend. Da hab ich wohl die Variable einmal geschaltet. Ich steig nur einfach nicht dahinter wieso der Adapter sporadisch alle Werte auf (null), (das heißt doch keine Werte oder?) schaltet.

Das der Controller den Adapter neustartet kann gut sein, da steht dann 

Initialisation finished, connected to Tado cloud service refreshing every 30 seconds

Während ich das hier schreibe, ist meine Freundin nach Hause gekommen und durch das mehrfache "neustarten" des Adapters ist der gesamte iobroker zusammengebrochen und hat sämtliche Adapter neustarten müssen.

Als iobroker Admin Oberfläche nutze ich die v5.2.3

und raspberryversion unter dem Reiter Host steht auf 3.3.22. Alles so weit auf dem neuesten Stand.

Habe vor dem tado-Adapter nur stable-Versionen und alles nach Anleitungen installiert. Lief auch seit einem Jahr problemlos.

Liegt der Fehler eventuell gar nicht am Adapter sondern an der iobroker Installation?

**Comment by HGlab01** [comment]
> Ich steig nur einfach nicht dahinter wieso der Adapter sporadisch alle Werte auf (null), (das heißt doch keine Werte oder?) schaltet.

Auf NULL werden die Werte geschalten, wenn bei der Abfrage keine Info vom Tado-Server dazu kommt.

**Comment by canim60** [comment]
> > Ich steig nur einfach nicht dahinter wieso der Adapter sporadisch alle Werte auf (null), (das heißt doch keine Werte oder?) schaltet.
> 
> Auf NULL werden die Werte geschalten, wenn bei der Abfrage keine Info vom Tado-Server dazu kommt.

Das wäre eigentlich meine Issue.
 Ich habe einen eigenen Vis, da benutze ich auch die Anzeige wie viel Grad bzw wie viel grad ich einstelle möchte. Die info bekomme ich nur dann,wenn die Heizung für den Raum an ist, Ist es aus, habe ich "null", kann man das irgendwie auf dem Objekt fest speichern?Sodass immer der letzte wert drin bleibt,statt "null" 
sieht dan so aus :)
![grafik](https://user-images.githubusercontent.com/66805899/148623634-17dc02fb-e84a-4a77-9330-919c02ca2e4d.png)

**Comment by TDCroPower** [comment]
> > > Ich steig nur einfach nicht dahinter wieso der Adapter sporadisch alle Werte auf (null), (das heißt doch keine Werte oder?) schaltet.
> > 
> > 
> > Auf NULL werden die Werte geschalten, wenn bei der Abfrage keine Info vom Tado-Server dazu kommt.
> 
> Das wäre eigentlich meine Issue. Ich habe einen eigenen Vis, da benutze ich auch die Anzeige wie viel Grad bzw wie viel grad ich einstelle möchte. Die info bekomme ich nur dann,wenn die Heizung für den Raum an ist, Ist es aus, habe ich "null", kann man das irgendwie auf dem Objekt fest speichern?Sodass immer der letzte wert drin bleibt,statt "null" sieht dan so aus :) ![grafik](https://user-images.githubusercontent.com/66805899/148623634-17dc02fb-e84a-4a77-9330-919c02ca2e4d.png)

Ja das kannst du ganze einfach lösen.
Hinter der Logik von AUS setzt du zusätzlich noch das er den aktuellen Wert aus tado.0.xxxxx.Rooms.xxxx.setting.temperature.celsius in einen Datenpunkt z.B. TempA schreibt.
Schaltest du per AN die Heizung wieder ein, wird aus dem Datenpunkt TempA der Datenpunkt tado.0.xxxxx.Rooms.xxxx.setting.temperature.celsius geschrieben, wodurch die Heizung einschaltet.
Dein VIS schaut dann nur auf den Wert von TempA und nicht auf den Datenpunkt vom Heizkörper selber.

**Comment by HGlab01** [comment]
Ist das Thema soweit erledigt?

**Comment by tigginho** [comment]
Ich behelfe mir mittlerweile durch Alexa-Routinen die ich über den ioBroker auslöse wenn bspw. ein Fenster geöffnet wird. 
Wenn ich versuche Temperaturwerte direkt im ioBroker zu ändern stürzt mir der tado-Adapter weiterhin sporadisch ab.

Ich komme so weit aber klar, kannst das hier schließen.
