### ISSUE TITLE
Cloud Login failed - "Error: Not yet logged in"

### ISSUE THREAD

**Issue by PhilJo99** [DrozmotiX/ioBroker.tado#414]
Hi,

I have recently installed the tado adapter (v 0.3.7). For some reason the adapter has the following error:

tado.0 | 2022-01-07 14:02:58.654 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2022-01-07 14:02:58.652 | error | **Error in data refresh at step getMet_data: Error: Not yet logged in**
tado.0 | 2022-01-07 14:02:58.650 | info | Connected to Tado cloud, initialyzing...

Logging in using the webbrowser works.

I do not have the tado prescription if that is important.

Thank you and regards,

Phil

**Comment by HGlab01** [comment]
Please upgrade to 0.3.13
If issue still exists check the internet connection from your iobroker server and double check the password in the adapter config.
More than 1000 other installation are working with 0.3.7 / 0.3.13. So it is to 99.99% that it is a config issue.

**Comment by Hartholz** [comment]
Hallo,
Ich habe das gleiche Problem.
Ist Username und Passwort das gleiche wie in der App?
Gibt es bei Username und Passwort etwas zu beachten bezüglich Sonderzeichen, Groß-Kleinschreibung, usw?
Vielen Dank
Andy

Hi there,
I have the same problem.
Is the username and password the same as in the app?
Is there anything to watch out for with username and password, regarding special characters, upper and lower case letters, etc.?
Many Thanks
Andy

**Comment by Hartholz** [comment]
tado.1 | 2022-01-10 13:52:53.054 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.1 | 2022-01-10 13:52:53.053 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password

**Comment by HGlab01** [comment]
> Hallo, Ich habe das gleiche Problem. Ist Username und Passwort das gleiche wie in der App?

Welche Adapter-Version?

**Comment by PhilJo99** [comment]
> Please upgrade to 0.3.13 If issue still exists check the internet connection from your iobroker server and double check the password in the adapter config. More than 1000 other installation are working with 0.3.7 / 0.3.13. So it is to 99.99% that it is a config issue.

Solved the problem for me!

Thanks for the quick and helpful support.

**Comment by Hartholz** [comment]
@HGlab01 
das Problem trat bei Version v0.3.7 auf nach upgrad auf v0.3.13 bekomme ich die selbe Fehlermeldung.

**Comment by HGlab01** [comment]
Starte den Adapter mal im Debug-Modus und speichere den gesamten Log als txt file.

**Comment by Hartholz** [comment]
Guten Morgen HGlab01,
mir ist es mittlerweile gelungen mich im Adapter anzumelden.
Nachdem ich das Gateway vom Strom getrennt und wieder verbunden habe, konnte der Adapter sich mit dem Gateway verbinden.
Vielen Dank für deine Mühe
Gruß
Andy
