### ISSUE TITLE
capabilities

### ISSUE THREAD

**Issue by ChrissT23** [DrozmotiX/ioBroker.tado#426]
fanSpeeds:AUTO,HIGH,MIDDLE,LOW swings:undefined canSetTemperature:undefined light:undefined

Die Nachricht kommt bei mir nach dem Update auf die aktuelle Version, die Steuerung des AC funktioniert aber wie vor dem Update auch.

**Comment by HGlab01** [comment]
Hallo! Danke für das Anlegen des Issues!
Kannst du mir bitte einen Screenshot der Datenpunkte zu
tado.x.yyyyy.Rooms.1.Capabilities
mit allen Datenpunkten "ausgeklappt" in das Issue hängen?
Dann kann ich die Adapter-Implementierung noch optimieren, dass es für alle Konstellationen klappt. Danke!

**Comment by ChrissT23** [comment]
reicht das so ? 

![4C28B354-3B01-42A7-8CD5-6590EDF989FB](https://user-images.githubusercontent.com/76846121/148649286-e3fd17b0-3c0f-45e6-810b-08cfb97c6572.jpeg)

**Comment by HGlab01** [comment]
ja, danke, super!

**Comment by HGlab01** [comment]
Input included in https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.3.14
