### ISSUE TITLE
actual_temperature 

### ISSUE THREAD

**Issue by Tripartius** [DrozmotiX/ioBroker.tado#441]
Ich hab den Adapter installiert, alle Objekte wurden erstellt, alle fünf Thermostate wurden erkannt.
Allerdings zeigen alle actual_temperature nur "(null) Grad C" an.

Damit kann ich nicht wirklich arbeiten, oder? Was braucht ihr für Angaben um mir zu sagen, was ich falsch mache oder falsch eingestellt habe? :)

Vielen Dank!

**Comment by sly-1** [comment]
Was genau meinst du mit "actual_temperatur"? 
Die aktuelle Temperatur steht in tado.x.xxxxxx.Rooms.x.sensorDataPoints.insideTemperature.celsius

**Comment by HGlab01** [comment]
> Was genau meinst du mit "actual_temperatur"? Die aktuelle Temperatur steht in tado.x.xxxxxx.Rooms.x.sensorDataPoints.insideTemperature.celsius

bzw.
tado.[x].[yyyyyy].Rooms.[z].setting.temperature.celsius
für die Solltemperatur
Siehe auch
https://github.com/DrozmotiX/ioBroker.tado#things-you-can-steer

**Comment by Tripartius** [comment]
Herrje, wie einfach kann es sein.
Ich habe nur in tado.x.xxxxxx.Rooms.x. die actual_temperature berücksichtigt. Keine Ahnung, was dass das für ein Wert ist, aber nicht der, den ich brauchte! 

Vielen Dank! Kann geschlossen werden!

**Comment by HGlab01** [comment]
ich würde vorschlagen du löscht mal manuell ALLE Datenpunkte und startest den Adapter neu damit nur mehr die Datenpunkte da sind, die auch bewirtschaftet werden
