### ISSUE TITLE
Gesetzter Temp Wert wird nicht mehr ausgelesen

### ISSUE THREAD

**Issue by TDCroPower** [DrozmotiX/ioBroker.tado#445]
**Describe the bug**  
Seit neuestem wird der gesetzte Temperatur Wert unter tado.0.xxxxx.Rooms.xxxx.setting.temperature.celsius nicht mehr aktualisiert, wenn man diesen am HKT oder per App ändert.
Ist mir erst seit kurzem aufgefallen, da ich diesen Datenpunkt mit meinem Blockly Script auslese für die Offset Berechnung und auch bei Öffnung des Fensters in eine Variable auslese, dabei haben die Ergebnisse dann überhaupt nicht mehr gestimmt.

**To Reproduce**  
1. Temperatur am HKT oder App ändern
2. den Datenpunkt tado.0.xxxxx.Rooms.xxxx.setting.temperature.celsius kontrollieren

**Versions:**  
 - Adapter version: 0.3.14
 - JS-Controller version: 3.3.22
 - Node version: v14.18.2
 - Operating system: Linux helios64 5.10.63-rockchip64 #21.08.2 SMP PREEMPT Wed Sep 8 10:57:23 UTC 2021 aarch64 GNU/Linux

**Comment by HGlab01** [comment]
Hallo! Danke für das Issue.
Kann ich mit 0.3.14 bei mir nicht nachvollziehen.
Kannst du bitte mal mit 0.3.14 und Debug-Modus ein log laufen lassen. Am besten so lange bis das Refresh-Intervall einmal erreicht ist und dann das Log hier posten. Danke!

**Comment by TDCroPower** [comment]
0.3.14-alpha.1 -> funktioniert
0.3.14-alpha.3 -> funktioniert
0.3.14-alpha.5 -> funktioniert
0.3.14 funktioniert jetzt auf einmal !?

**Comment by HGlab01** [comment]
No idea why ;-)
Aber wie gesagt, an dem Abholn der Werte hat sich schon seit 0.3.7 nichts mehr geändert...

**Comment by TDCroPower** [comment]
Ich mach hier mal dicht, ist ja komischerweise nicht reproduzierbar.
