### ISSUE TITLE
capabilities

### ISSUE THREAD

**Issue by j-r79** [DrozmotiX/ioBroker.tado#452]
WE NEED YOUR HELP! Your AC-Tado-Setup is not yet supported!

Please raise a ticket by using this URL 'https://github.com/DrozmotiX/ioBroker.tado/issues/new?labels=support&title=capabilities&body=fanSpeeds:AUTO,HIGH,MIDDLE,LOW%20swings:undefined%20canSetTemperature:undefined%20light:undefined'

Pleas add this info to the ticket (if not automatically done): 'fanSpeeds:AUTO,HIGH,MIDDLE,LOW swings:undefined canSetTemperature:undefined light:undefined'

fanSpeeds:AUTO,HIGH,MIDDLE,LOW swings:undefined canSetTemperature:undefined light:undefined

**Comment by HGlab01** [comment]
Thanx!

**Comment by j-r79** [comment]
if you need more/other data, test a change, etc...

Just give me a hint.

**Comment by HGlab01** [comment]
Thanks, so far its fine.
If you upgrade to 0.3.14 I assume your device should work fine
