### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by andrePKI** [DrozmotiX/ioBroker.tado#462]
Could you please provide some basic information in the Readme? Like what do you get with this, platform, prequisites, how to get started etc

**Comment by HGlab01** [comment]
Hi @andrePKI!
Thanks for the hint, Sure, we can add additional info.
As you maybe know better what information is most interesting I highly appreciate a pull request or just add a couple of lines in this issue and I will add it to the readme.

**Comment by HGlab01** [comment]
Any reaction?

**Comment by andrePKI** [comment]
Of course not, how can I add what I don't know...
