### ISSUE TITLE
Adapter Restart bei Temperaturänderungen / Warnhinweise nach Update auf Iob 4.0.15

### ISSUE THREAD

**Issue by Lomeyer** [DrozmotiX/ioBroker.tado#485]
Guten Abend,

seit dem Update des JS Controllers auf 4.0.15 gibts ein bisschen Probleme mit dem Adapter.

**Versions:**  
 - Adapter version: 0.3.14
 - JS-Controller version: 4.0.15
 - Node version: 12.22.9, ab spätem Vormittag im Logfile ist es dann 14.19.0
 - Operating system: Debian Bullseye

Nach dem Update schrieb der Adapter erstmal fleißig das Log voll (nur ein Beispiel):

`<p>2022-02-26 10:28:39.228  - [33mwarn[39m: tado.0 (12304) Object online is invalid: obj.common.states has an invalid type! Expected "object", received "string"`
`2022-02-26 10:28:39.230  - [33mwarn[39m: tado.0 (12304) This object will not be created in future versions. Please report this to the developer.`

Nach dem Update auf node-js 14.19.0 war es wieder so (siehe Logfile).

Hinzu kommt, dass bei Änderungen der Temperatur (beispielhaft) `tado.0.491280.Rooms.2.setting.temperature.celsius` immer mal wieder alle Aktualwerte der Tado-Geräte auf (Null) gehen. 

Ab 23:03 stand der Adapter dann auf debug.

Bei Rückfragen bitte melden, auch gerne Kritik am Issue-Report äußern, ist mein erster ;)
[Debug_Log_Tado.log](https://github.com/DrozmotiX/ioBroker.tado/files/8147648/Debug_Log_Tado.log)

**Comment by HGlab01** [comment]
Hallo, bitte auf 0.3.15 upgraden. Dann sollten die Logs weg sein.
Wenn das Thema mit "null" noch auftritt nach dem Update bitte nochmals in dem Issue melden. Danke!

**Comment by Lomeyer** [comment]
Vielen Dank fürs Update, Fehler ist verschwunden:)
