### ISSUE TITLE
light not in supported light [ON, OFF]

### ISSUE THREAD

**Issue by blacktiger333** [DrozmotiX/ioBroker.tado#519]
AC Power Off works - but with Power On there is an error because light attribute hasn't a wrong value (null). fanLevel/horizontalSwing/light/mode are switched to null after one second if Power Off command has sent. 
<html><body>

tado.0 | 2022-07-22 11:58:24.699 | error | Issue  at setZoneOverlay: 'Error: Request failed with status code 422'. Based  on config  {"setting":{"type":"AIR_CONDITIONING","power":"ON","mode":"COOL","temperature":{"celsius":20},"horizontalSwing":"OFF","verticalSwing":"OFF","fanLevel":"AUTO"},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
-- | -- | -- | --
tado.0 | 2022-07-22 11:58:24.699 | error | Error:  Request failed with status code 422 with response  {"errors":[{"code":"setting.notSupported","title":"light not in  supported light [ON, OFF]"}]}

</body>
</html>

**Comment by HGlab01** [comment]
On vacation. Will check next week
Please explain a bit what the light attribute is good for. Thanks!

**Comment by HGlab01** [comment]
please test with 0.3.16-alpha.0
