### ISSUE TITLE
aktuelle Heizleistung in Prozent pro Gerät und nicht nur per Raum

### ISSUE THREAD

**Issue by iPhilBln** [DrozmotiX/ioBroker.tado#535]
Hej, 
eigentlich bin ich  großer Fan des Tado Systems. Leider ist es aber manchmal so, dass sich nicht alle Thermostate im Raum richtig synchronisieren, sodass es unter Umständen vorkommt, dass zB ein Thermostat auf volle pulle heizt und das andere eiskalt bleibt. 
Da dies aber nicht nur bei einem Thermostat so ist und auch keine Verbindungsprobleme bestehen, denke ich, wird es ein generelles Problem sein. 

Wäre es daher möglich, den Datenpunkt der aktuellen Heizleistung pro Gerät zur Verfügung zu stellen und nicht nur per Raum? 
Dann könnte man ggf. versuchen dem entgegenzuwirken. Man müsste dann zwar noch einzelne Geräte ansteuern können, aber das sollte ja möglich sein meines Wissens.

**Comment by HGlab01** [comment]
Hallo! Gibt es in der App diese Info? Wenn ja wo/wie?

**Comment by iPhilBln** [comment]
> Hallo! Gibt es in der App diese Info? Wenn ja wo/wie?

Gut, ich schließe dann mal das feature request. Hab mich jetzt auch mal etwas durch die API geforstet was man so finden kann unter: [Tado API](https://community.home-assistant.io/t/read-new-tado-api-features/351521) und per CLI etwas durchgeschaut. Scheint tatsächlich nur per Zone auslesbar zu sein. Schade.
