### ISSUE TITLE
Disconnected from Tado cloud service

### ISSUE THREAD

**Issue by Uwe1984** [DrozmotiX/ioBroker.tado#547]
Seit einiger Zeit habe ich mehrmals am Tag einen Neustart des Tado Adapters mit folgenden errors
`<html>
<body>

tado.0 | 2022-11-04 11:56:08.863 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
-- | -- | -- | --
tado.0 | 2022-11-04 11:56:08.853 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password

</body>
</html>`

Der Adapter verbindet sich dann wieder mit der Tado Cloud und alle läuft wieder. 
Node.js  16.18.0
NPM 8.19.2
js-controller 4.0.23

Im Forum habe ich darauf keine Lösung gefunden. 
Könnte mir hier eventuell ein Entwickler helfen?

**Comment by HGlab01** [comment]
Hallo,
das ist kein Neustart des Adapters sondern beim Versuch Daten vom Server abzuholen gibt es Kommunikationsproblem.
Kann am Tado-Server liegen (der hat immer wieder mal Aussetzer) oder an deinem Netzwerk.
Am Adapter liegt es wohl nicht, da es keine vermehrten Meldungen über Sentry gibt.

**Comment by ChristianGrieger** [comment]
Habe mir jetzt ein Thermostat zum testen gekauft & eingebaut und bekomme laufend die folgenden Fehler:
<img width="1039" alt="Bildschirm­foto 2022-11-19 um 11 58 42" src="https://user-images.githubusercontent.com/8712219/202847372-30460aaa-965c-4ef1-bdeb-3faf1c23ff8b.png">

**Comment by Apollon77** [comment]
EAI_AGAIN getaddrinfo heisst das die DNS AUflösung des domainnamens nicht möglich ist. Bitte DNS/Netzerk Konfig des Hosts prüfen. Hat an sich nichts mit dem Adapter zu tun

**Comment by ChristianGrieger** [comment]
> EAI_AGAIN getaddrinfo heisst das die DNS AUflösung des domainnamens nicht möglich ist. Bitte DNS/Netzerk Konfig des Hosts prüfen. Hat an sich nichts mit dem Adapter zu tun

Kannst du mir sagen was ich genau machen muss, oder wie ich dem Problem lösen kann? Habe sonst keine Probleme im Netzwerk oder mit anderen Adaptern. Danke.

<img width="1095" alt="Bildschirm­foto 2022-11-27 um 17 06 50" src="https://user-images.githubusercontent.com/8712219/204145144-fb7f6906-1b3a-4a3a-a1eb-994cfaa712cb.png">
