### ISSUE TITLE
Batteriestatus & States

### ISSUE THREAD

**Issue by ChristianGrieger** [DrozmotiX/ioBroker.tado#548]
Guten Morgen,

mich würde interessieren ob ich mit dem Adapter den Batteriestatus abfragen kann? 
Wo liegen die Datenpunkte und welche genauen States liefern diese zurück? Gibt es einen % Wert und einen IsLow Wert?

Ich überlege auf Tado umzustellen und wollte dies vorher geklärt haben.

Vielen Dank.

**Comment by HGlab01** [comment]
es gibt pro Device einen batteryState.
Der State zeigt "NORMAL" an wenn die Batterie ok ist. Vermutlöich gibt es noch einen oder zwei weitere States.
Die Batterie hält auch deutlich mehr als ein Jahr.

**Comment by ChristianGrieger** [comment]
Okay, kann man die anderen States neben "NORMAL" irgendwo einsehen?

**Comment by HGlab01** [comment]
ich weiß es nicht welche States die Tado-API liefert, das ist bei Tado nicht dokumentiert
Vielleicht kann es dir jemand im Forum beantworten
https://forum.iobroker.net/topic/45301/test-adapter-tado-v0-3-0-x-prerelease

**Comment by ChristianGrieger** [comment]
Hmm, okay dann höre ich mal nur den NORMAL State up und reagiere wenn dieser sich ändert.
