### ISSUE TITLE
Overlay termination - All values null

### ISSUE THREAD

**Issue by ChristianGrieger** [DrozmotiX/ioBroker.tado#549]
Wenn ich es richtig verstanden habe, kann ich `tado.[x].[yyyyyy].Rooms.[z].overlay.termination.typeSkillBasedApp` zum fortfahren des Zeitplans benutzen? Leider sind alle Values (null) und beim Umstellen wird nichts ausgelöst.

<img width="1757" alt="Bildschirm­foto 2022-11-19 um 13 38 36" src="https://user-images.githubusercontent.com/8712219/202851292-f41da089-26c7-4bbf-9074-b32776b99165.png">

**Comment by HGlab01** [comment]
Was man steuern kann steht hier
https://github.com/DrozmotiX/ioBroker.tado#things-you-can-steer
Wenn die Werte bei "Overlay" gleich NULL sind, heißt es, dass es kein Overlay gibt. Also bist du bereits im Automatik-Modus.
Ich vermute es wird auch
tado.x.yyyyy.Rooms.z.overlayType gleich NULL sein? Sonst wäre er auf zB MANUAL

Bei tado.[x].[yyyyyy].Rooms.[z].overlay.termination.typeSkillBasedApp solltest du eine Liste von Werten zur Auswahl haben
![image](https://user-images.githubusercontent.com/54232526/202852521-c02a4759-96ae-41ec-bd33-e57fb6dec929.png)

**Comment by ChristianGrieger** [comment]
Die Werte habe ich gesehen. Ich meine aber wie ich den Overlay deaktivieren kann. Ich habe dies online gefunden und werde es mal testen: tado.0.xxxxx.Rooms.10.overlayClearZone

**Comment by HGlab01** [comment]
Overlay bedeutet, dass die Automatik überlagert ist
Man kann es daher nur deaktivieren wenn es aktiviert ist Solange die Werte im Overlay NULL sind, ist man im Automatik-Modus.
Mit tado.[x].[yyyyyy].Rooms.[z].overlayClearZone kommt man wieder in den Atuomatikmodus
