### ISSUE TITLE
"nextTimeBlock" wird nicht geupdatet V 0.4.1

### ISSUE THREAD

**Issue by senger1985** [DrozmotiX/ioBroker.tado#560]
Der Datenpunkt "nextTimeBlock" steht bei mir noch auf dem vorherigem Block und zeigt mir die auch die SOLL-Temperatur, des Zeitblocks an, welcher eigentlich schon abgelaufen ist.
Der Datenpunt wurde zuletzt am 25.11., um 11:15 geändert, laut Zeitstempel, obwohl sich der neue Zeitblock um 00:00 Uhr geändert hat.
In der App wird aber der richtige Zeitblock und auch die richtige Temperatur angezeigt, die eingestellt sein soll.

**Versions:**  
 - Adapter version: V0.4.1
 - JS-Controller version: V4.0.23
 - Node version: V16.17.0
 - Operating system: Proxmox-Container

**Comment by TDCroPower** [comment]
Ich habe das gleiche mit dem Datenpunkt "power" unter Home >>> Rooms >>> Number >>> setting.
Schalte ich den HKT aus/an, verändert sich der Datenpunkt nicht.
Unter 0.4.0 funktioniert es weiterhin, wenn ich die Version downgrade.

**Comment by HGlab01** [comment]
gibt es irgendwelche Log-Einträge?
Wie sieht es mit Datenpunkten wie zB 
tado.x.yyyyyyy.Rooms.z.sensorDataPoints.insideTemperature.celsius
aus? Gibt es hier auch kein Update?

Meine Tado-Geräte werden mit 0.4.1 alle sauber upgedated. Tappe derzeit noch im Dunkeln....#

Wenn es im Log nichts gibt bitte mal den Adapter in den Debug-Modus wechseln und dann das Log posten. Danke!

**Comment by senger1985** [comment]
@HGlab01 
<html>
<body>


tado.0 | 2022-11-26 22:15:44.047 | warn | Sentry disabled, error catched: Error: DB closed
-- | -- | -- | --
tado.0 | 2022-11-26 22:15:44.046 | error | Error in function stateSetCreate(): Error: DB closed


</body>
</html>

**Comment by HGlab01** [comment]
please check if it works with version 0.4.2 (selectable in iobroker by tomorrow)
https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.4.2

**Comment by TDCroPower** [comment]
@HGlab01 thanks, I'll test the version directly tomorrow when it's online.

**Comment by TDCroPower** [comment]
@HGlab01 die 0.4.2 funktioniert!

**Comment by HGlab01** [comment]
fixed in https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.4.2
