### ISSUE TITLE
Temperatur einzelner Thermostate in einem Raum

### ISSUE THREAD

**Issue by SchlumpfIOB** [DrozmotiX/ioBroker.tado#574]
Hallo Ihr,

ich weiß nicht ob ich das hier richtig betietelt habe bzw. unter dem Richtigen erstellt habe. verzeit wenn es falsch ist und verschiebt es gerne.

Ich benötige einen zusätzlichen Wert und würde mich freuen wenn das einfach umsetzbar ist (und jemand machen könnte (*liebguckendersmiley*). Es geht um die Temperatur der einzelnen Devices in einem Raum, vor der Anpassung durch "offset", sprich den wirklich gemessenen Wert des jeweiligen Termostates.

Ich habe folgende Aufgabenstellung:

Bei mir sind die Heizungen (2 Stück) im Wohnzimmer (ein Raum der Esszimmer, Stube, Flur und Küche mit einschließt) sehr nach an der Außenwand und etwas "separat". Geheizt wird derzeit mit einem Kaminofen (Holz). Das Problem ist, dass die Wärme nicht gut an die Stellen der Thermostate kommt und sie deshalb und aufgrund der kühleren Außenwände immer einige Grad weniger anzeigen als wirklich sind (zumindest da wo sich am meisten aufgehalten wird). Ziemlich zentral steht eine Wetterstation von Netatmo, welche relativ gut die Temperatur wiedergibt.

Nun möchte ich gerne, um die Heizung nicht dauerhaft laufen zu lassen obwohl es schön warm ist, die Temperatur der Thermostate auf die der Wetterstation einstellen. Direkt geht dies leider nicht, aber es würde über den Umweg des Wertes "offset" gehen, vorrausgesetzt ich habe den unverfälschten Wert (Temperatur) der einzelnen Thermostate. So kann ein Skript erstellt werden, welche die Temperatur des steuernden Thermostates mit der Temperatur der Wetterstation verrechnet und das Ergebnis als "offset" einträgt.

Gibt es diesen Wert und kann er zur Verfügung gestellt werden? Evtl. auch ein "offset"-Wert nur für den Raum, separat von dem der Thermostate?

Gruß
Jan

**Comment by HGlab01** [comment]
Hallo,

du kannst in einem JS einen Listener auf
tado.0.xxxx.Rooms.y.devices.RUzzzzz.offset.offsetCelsius
und
tado.0.xxxxxx.Rooms.y.sensorDataPoints.insideTemperature.celsius
hängen und wenn sich einer der beiden Werte ändert die Berechnung durchführen.

Sollte das nicht dein sehr spezifisches Problem lösen?

Für einen Einbau im Adapter ist es meiner Meinung nach zu spezifisch.

**Comment by TDCroPower** [comment]
@SchlumpfIOB ... es gibt doch den offset Wert als Datenpunkt unter...
tado.0.xxxx.Rooms.xx.devices.VAxxxx.offset.offsetCelsius

und den gemessen Tado Temperatur Wert (Achtung hier wurde der Offset einberechnet) unter...
tado.0.xxxx.Rooms.xx.setting.temperature.celsius

um den Tado Temperatur Wert zu erhalten einfach folgendes im Script berechnen...
celsius - Offset = gemessener Temperatur

Diesen kannst du dann mit deiner Wetterstation vergleichen und die Differenz als Offset auf den Offset Datenpunkt schreiben, so nähert sich der Tado an die Wetterstation und die beiden sind schnell synchron.
Ich lass den Abgleich alle 30 Minuten durchlaufen.
