### ISSUE TITLE
Disconnect and wrong credentials

### ISSUE THREAD

**Issue by Gosuwaldbear** [DrozmotiX/ioBroker.tado#582]
Tado: v0.4.3
Admin: v6.3.5
node.js: v16.19.0
npm: 8.19.3
Interval: 60 sec
Username and Password are correct.

tado.0 | 2023-01-07 11:53:44.851 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 11:53:44.850 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 11:53:44.850 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 11:48:50.867 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 11:48:50.865 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 11:48:50.864 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 11:37:25.041 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 11:37:25.039 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 11:37:25.039 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 11:36:54.496 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 11:36:54.495 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 10:57:03.826 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 10:57:03.824 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 10:36:43.061 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 10:36:43.059 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 10:36:43.058 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 10:15:55.269 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 10:15:55.269 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo EAI_AGAIN my.tado.com
tado.0 | 2023-01-07 10:15:55.269 | error | Error: getaddrinfo EAI_AGAIN my.tado.com
tado.0 | 2023-01-07 10:12:55.994 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 10:12:55.993 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 09:36:13.459 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 09:36:13.457 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 09:36:13.456 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 09:11:30.822 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 09:11:30.822 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 09:08:42.481 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 09:08:42.480 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 08:50:41.282 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 08:50:41.281 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 08:45:43.762 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 08:45:43.762 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 08:44:07.690 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 08:44:07.690 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:44:07.690 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:40:10.790 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 08:40:10.788 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:40:10.787 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:26:29.121 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 08:26:29.120 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:26:29.120 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:24:51.434 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 08:24:51.432 | error | Error in data refresh at step DoZones: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:24:51.431 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:13:16.004 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 08:13:16.001 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 08:13:16.000 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:50:43.722 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 07:50:43.721 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 07:47:57.576 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 07:47:57.574 | error | Error in data refresh at step DoZones: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:47:57.573 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:35:18.431 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 07:35:18.430 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:35:18.430 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:27:01.286 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 07:27:01.284 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:27:01.283 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:12:06.824 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 07:12:06.823 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:12:06.823 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:11:34.760 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 07:11:34.758 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 07:11:34.757 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:50:08.096 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:50:08.093 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:50:08.093 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:49:37.539 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:49:37.538 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 06:41:25.398 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:41:25.398 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo EAI_AGAIN my.tado.com
tado.0 | 2023-01-07 06:41:25.398 | error | Error: getaddrinfo EAI_AGAIN my.tado.com
tado.0 | 2023-01-07 06:37:36.773 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:37:36.773 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:37:36.773 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:36:02.143 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:36:02.141 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:36:02.141 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:30:00.382 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:30:00.381 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 06:12:55.274 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:12:55.272 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:12:55.271 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 06:04:43.061 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 06:04:43.061 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo EAI_AGAIN my.tado.com
tado.0 | 2023-01-07 06:04:43.061 | error | Error: getaddrinfo EAI_AGAIN my.tado.com
tado.0 | 2023-01-07 05:59:48.176 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 05:59:48.175 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 05:57:07.825 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 05:57:07.825 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 05:53:18.297 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 05:53:18.296 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 05:53:18.296 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 05:48:22.652 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 05:48:22.649 | error | Error in data refresh at step DoZones: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 05:48:22.649 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 05:19:17.990 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 05:19:17.988 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 05:19:17.988 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 05:18:47.585 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 05:18:47.584 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 04:58:32.769 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:58:32.767 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 04:58:32.766 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 04:38:17.227 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:38:17.227 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 04:35:36.933 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:35:36.931 | error | Error in data refresh at step DoZones: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 04:35:36.930 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 04:18:24.782 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:18:24.782 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 04:13:31.859 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:13:31.856 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 04:13:31.855 | error | Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 04:07:30.757 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:07:30.757 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 04:03:44.434 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:03:44.433 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2023-01-07 04:02:08.633 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2023-01-07 04:02:08.631 | error | Error in data refresh at step DoMobileDevices: Error: getaddrinfo ENOTFOUND my.tado.com
tado.0 | 2023-01-07 04:02:08.631 | error | Error: getaddrinfo ENOTFOUND my.tado.com

**Comment by HGlab01** [comment]
Please check your network!
`getaddrinfo ENOTFOUND my.tado.com`
means that the adapter 8and so your host) was not able to do the DNS lookup for the given domain.
Nothing that can be done on adapter side.
