### ISSUE TITLE
Bitte um Hilfestellung bei Tado Klimaanlagensteuerung V3

### ISSUE THREAD

**Issue by buchse12** [DrozmotiX/ioBroker.tado#601]
Hallo,
super, dass es einen Adapter für Iobroker gibt. Leider finde ich nirgends eine Anleitung welche Werte gesetzt werden müssen.
Um den Adapter zu testen habe ich über Blockly ( oder auch manuell)
folgende Werte setzt:
tado.[x].[yyyyyy].Räume.[z].setting.power  >>True
tado.[x].[yyyyyy].Räume.[z].Einstellung.Temperatur.Celsius  >>26
Leider passiert nichts, wenn ich die Daten dort hineinschreibe. Diese werden sofort wieder gelöscht.
Was muss ich machen, oder gibt es irgendwo eine Dokumentation, wie die Vorgehensweise ist?

Danke für eine Hilfestellung.
Gruß Mark

**Comment by sly-1** [comment]
Hi Mark, 
du könntest zum Testen als erstes direkt in den Objekten einen Wert ändern. 
Zum Beispiel das Gerät EIN/AUS schalten oder die Temperatur ändern. 
`tado.[x].[yyyyyy].Rooms.[z].setting.temperature.celsius` Hier eine andere Temperatur angeben. 
`tado.[x].[yyyyyy].Rooms.[z].setting.power` Hier den Wert von **ON** in **OFF** ändern. 
![Beispiel](https://user-images.githubusercontent.com/59330827/217612049-0a595ee6-0be0-4d28-a777-ef215430ee7b.png)
Das sollte eigentlich funktionieren.

**Comment by HGlab01** [comment]
Hallo, was gesteuert werden kann steht hier
https://github.com/DrozmotiX/ioBroker.tado#things-you-can-steer

Wenn eine Ändeurng bei `tado.[x].[yyyyyy].Rooms.[z].setting.temperature.celsius` oder `tado.[x].[yyyyyy].Rooms.[z].setting.power` nicht funktioniert, dann hat es was. Dann wäre das Log interessant/notwendig zum dir zu helfen.

**Comment by buchse12** [comment]
Moin, Vielen Dank für Euer Input. Ich habe es heute nocheinmal ausprobiert und nun bleiben die Werte (z.B Temperatur) nach dem setzten auch erhalten. Gestern wurden diese sofort wieder auf [null] gesetzt.

wenn ich das per Blockly steuern möchte. Sollte man bei dem Setzen der Werte immer eine Pause von ein paar ms setzen, oder eine bestimmte Reihenfolge einhalten?
Temperatur / Mode / verticalSwing


Vielen Dank.

**Comment by HGlab01** [comment]
Alle zeitgleich setzen. Der Adapter wartet ein paar Millisekunden die Daten zusammen bevor er sie sendet.
Damit wird nur ein Call abgesetzt und Reihenfolge ist egal.
