### ISSUE TITLE
Klimasteuerung V3+, lässt sich per ioBroker bedienen, ausschalten, jedoch nicht einschalten. 

### ISSUE THREAD

**Issue by Lendelfinger** [DrozmotiX/ioBroker.tado#625]
Klimaanlagensteuerung V3+ lässt sich mittels Datenpunkten im ioBroker bedienen, wenn das Gerät (von extern) eingeschaltet wurde.

Wenn es aus ist und man den Datenpunkt "tado.[x].[yyyyyy].Räume.[z].setting.power" auf "on" stellt, springt dieser auf grün, kurz danach auf rot und nach wenigen Sekunden auf "OFF". Gerät bleibt aus.

Aufgefallen ist mir: wenn das Gerät "an" ist, sind folgende Werte vergeben:

tado.[x].[yyyyyy].Räume.[z].setting.temperature.celsius
tado.[x].[yyyyyy].Räume.[z].setting.temperature.fahrenheit
tado.[x].[yyyyyy].Räume.[z].setting.fanLevel
tado.[x].[yyyyyy].Räume.[z].setting.horizontalSwing
tado.[x].[yyyyyy].Räume.[z].setting.mode
tado.[x].[yyyyyy].Räume.[z].setting.power
tado.[x].[yyyyyy].Räume.[z].setting.type
tado.[x].[yyyyyy].Räume.[z].setting.verticalSwing

Schalte ich es aus, werden diese Werte (außer Power und Type) nach einigen Sekunden auf (NULL) gesetzt. Versuche ich vor dem "(NULL) setzen" (also wenn die Werte noch vergeben sind), wieder auf "on" zu schalten, funktioniert es. 
Sind die Werte aber bereits auf (NULL), tritt der Fehler auf und die Anlage lässt sich nicht mehr über den ioBroker aktivieren.

getetest mit 0.4.5 und 0.4.6-alpha.2

**Comment by HGlab01** [comment]
Hallo! Das ist leider von AC Gerät zu AC Gerät unterschiedlich. Da kann ich am Adapter selbst nichts ändern.
Bei anderen Geräten reicht Power auf ON
