### ISSUE TITLE
Mehrere Thermostate/ Temperatursensoren in einem Raum

### ISSUE THREAD

**Issue by fabssor** [DrozmotiX/ioBroker.tado#646]
Hallo zusammen,

vorab ich bin absoluter iobroker Neuling und versuch mich grad zurecht zu finden :)

Ich möchte über yahka meine Thermostate steueren bzw. die Temperaturwerte anzeigen.
In einem Raum habe ich mehrere Thermostate bzw. Temperatursensoren (beides von tado). Diese sind auch einem Raum in der tado App zueordnet.
Ich würde gern (einfach weil das Tado selber auch nativ kann über die Homekit Integration) die Sensor-Werte vom Temperatursensor in Home zusätzlich einzeln anzeigen. 
Pro Raum finde ich aber nur eine Temperatur (die Temperatur des Gerätes welches als messendes Gerät für den Raum über tado eingestellt ist). Temperaturen/ Luftfeuchte pro Gerät finde ich nicht im Baum. 

Ist das eine Limitation von tado?

Fabian

**Comment by HGlab01** [comment]
Guten Morgen!
Interessantes Feature ;-)
Mehere Temp.sensoren in einem Raum kannte ich bisher nicht. Wie stellt dies die Tado-App dar bzw. sieht man diese mehreren Temperaturen auch in der Web-App (https://app.tado.com/)
Wenn ja, dann könnten wir eine gemeinsame Debug-Session machen um zu sehen ob/wie ich an die Daten für den ioBroker-Adapter komme...

**Comment by fabssor** [comment]
Hey! 
In der tado App werden die Temperaturen tatsächlich nicht einzeln angezeigt sonder nur "pro Raum". Unter Geräte kann man das messende Gerät auswählen, wenn mehrere Thermostate/ Temperatur-Sensoren einem Raum zugeordnet sind. 
Die native Tado-Homekit integration zeigt aber dann sowohl Temperatur-Sensor und Thermostat einzeln in "Home" an.

**Comment by HGlab01** [comment]
ich konnte leider keine Infos finden, welche API diese Daten liefert :-(
