### ISSUE TITLE
Please add sentry information to README.md

### ISSUE THREAD

**Issue by mcm1957** [DrozmotiX/ioBroker.tado#710]
- [ ] This adapter seems to use sentry, but no sentry info is added to Readme.md
  
  This adapter seems to use sentry for error logging. Please add the suggested sentry information at the top of Readme.md
  
  ```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```

**Comment by HGlab01** [comment]
fixed https://github.com/DrozmotiX/ioBroker.tado/commit/7eb408602004e3a1a5f6563308699a4bdd754948
