### ISSUE TITLE
Aus Javaskript nicht Steuerbar!

### ISSUE THREAD

**Issue by ForwardThinkerDev** [DrozmotiX/ioBroker.tado#716]
Problem: 
In Objekte kann ich es steuern und der Tado Server schaltet um. (sehe ich in der APP).
Im Javaskript Code sehe ich die Änderung zwar in Objekte aber der Server schaltet nicht um.

```
// Setze den Wert von 'tado.0.1259119.Home.state.presence' auf "Away"
setState('tado.0.1259119.Home.state.presence', 'Away', true);
```

**Comment by DutchmanNL** [comment]
Das liegt ein deinem Code, du setzt den ack auf true damit reagiert de Adapter nicht

Probier es mal so setState('tado.0.1259119.Home.state.presence', 'Away', false);

**Comment by HGlab01** [comment]
Und es sollte `AWAY` und nicht `Away` gesetzt werden - Display vs. Data value
