### ISSUE TITLE
Energy IQ Werte schreiben.

### ISSUE THREAD

**Issue by Forestarius** [DrozmotiX/ioBroker.tado#751]
Hallo, 

Gibt es die Möglichkeit in der API, die "Gaszählerstände" im Addon Energy IQ einzutragen. 

Ich erfasse meinen Gaszählerstand im Iobroker über einen Reedkontakt an der Gasuhr, Es wäre eine smarte Lösung, wenn man diesen Wert im Adapter direkt hineinschreiben könnte. z.B. über Blockly einmal täglich.

**Comment by HGlab01** [comment]
I sehe mir das mal wenn ich ein wenig mehr Zeit hab an. Könnte aber eine harte Nuss werden. API-Doku dazu gibt es wie für vieles andere keine.

**Comment by HGlab01** [comment]
Erste Infos:

GET
https://energy-insights.tado.com/api/homes/xxxxx/meterReadings?ngsw-bypass=true

POST
https://energy-insights.tado.com/api/homes/xxxxx/meterReadings?ngsw-bypass=true
{
  "date": "2023-11-27",
  "reading": 9999
}

**Comment by Forestarius** [comment]
Ja nur kein Stress. Ist nur ein nettes gimmick nice to have. Der Adapter bietet ja schon allerhand Möglichkeiten

**Comment by Forestarius** [comment]
Leider kann ich mit den Links nichts anfangen, hab mich zwischenzeitlich damit beschäftigt, kommt aber immer wieder "authentication failed"

**Comment by HGlab01** [comment]
Diese Infos https://github.com/DrozmotiX/ioBroker.tado/issues/751#issuecomment-1828437630 waren für mich als erste Info, wie es klappen könnte
Hab aber bisher mir die Zeit noch nicht genommen das mal genauer anzusehen

**Comment by SoerenKaiser99** [comment]
schaut mal hier: https://www.home-assistant.io/integrations/tado/
vielleicht hilft das weiter:

You can use the tado.add_meter_reading action to add your meter readings to Tado Energy IQ

`# Example automation add meter readings on a daily basis.
automation:
    # Trigger on specified time.
    trigger:
      - platform: time
        at: "00:00:00"

    # Add meter readings from `sensor.gas_consumption` to Tado.
    # Retrieve your `config_entry` id by setting this automation up in UI mode.
    # Notice that you may have to convert the reading to integer.
    action:
      - action: tado.add_meter_reading
        data:
          config_entry: ef2e84b3dfc0aee85ed44ac8e8038ccf
          reading: "{{ states('sensor.gas_consumption')|int }}"`

**Comment by HGlab01** [comment]
Ich komme nun endlich dazu das zu implementieren - also wenn noch relevant für dich freue mich über einen Tester in den nächsten Tagen ;-)

**Comment by Forestarius** [comment]
Hey kein Thema, sag bescheid wenn du soweit bist und dann probiere ich gerne aus

**Comment by Forestarius** [comment]
Hi, 
Vielen Dank für deine Arbeit, habe es ausprobiert und lasse es jetzt täglich per Java Script schreiben. 
Funktioniert bisher ohne Probleme.

Gruß Frank

**Comment by HGlab01** [comment]
Feature ist nun auch in Version 0.5.7-alpha.1 drinnen
`iob upgrade iobroker.tado@0.5.7-alpha.1`
