### ISSUE TITLE
surprisingly high numbers of requests to my.tado.com

### ISSUE THREAD

**Issue by LeoTronick** [DrozmotiX/ioBroker.tado#753]
If this is known and intended behavior, let me know and I will bother no more.
First, thanks for this nice adapter. It helps my automation with tado a lot.

After recently adding AdGuard home to my network my eyes fell on a surprisingly high number of requests to my.tado.com from the machine which runs iobroker and the tado adpter. It seems not to be altered by my automations running based on the adapter since stopping them does not change the numbers.
If I leave the adapter running, just collecting data, I see ~65k requests to my.tado.com per 24h.
I have set my instance to an update interval of 60s and get around 50 requests every 60s. 

![image](https://github.com/DrozmotiX/ioBroker.tado/assets/27626959/3f080665-c60d-416b-8f8b-91fc577f48e7)

Using version 0.5 on
- Plattform: linux
- RAM: 1.8 GB
- Node.js: v18.17.1(18.19.0)
- NPM: 10.2.3
- JS controller 5.0.16

**Comment by HGlab01** [comment]
Good evening,

how many Tado-devices are installed in our system?
50 is more than I would expect in a typical system, but it is not super extrem.

Tado has a huge set of tiny API calls and it is needed to request all of them to get the holistic view.
I counted my calls and there are 16 calls (for 2 rooms with 1 device per room)

If you like you can install this version
`DrozmotiX/ioBroker.tado#5cc56f72134988df6c345337664c9eea17f3ffb1`

![image](https://github.com/DrozmotiX/ioBroker.tado/assets/54232526/9bdc364e-b10b-465e-8c5b-8fd5f4161fad)

There you see in the log all "GET" requests and you can share it here.

**Comment by LeoTronick** [comment]
Alright.
I have 5 Tado valves and one room thermostat. So it might be just the normal amount. 
I will go with the suggested version and report back anyway.
Thanks
