### ISSUE TITLE
Aktualisierung der Daten stoppt nach einer gewissen Zeit 

### ISSUE THREAD

**Issue by cracyfloyd** [DrozmotiX/ioBroker.tado#813]
**!!! Before you start !!!**  
1. Verify if there is not already an issue requesting the same
2. Is this really a bug of current code, or an enhancement request ?

**Describe the bug**  
Nach einer unbestimmten Zeit beendet der Adapter die Aktualisierung der Daten. Dabei entsteht kein Fehler. Nach einem Neustart des Adapters aktualisiert er die Daten dann wieder für ein paar Stunden und stoppt dann wieder mit der Aktualisierung. Dieses passiert 2 - 3 mal die Woche. Die Internetverbindung ist immer online.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  

Im Screenshot kann man schön erkennen das er  z.B am 22.05 ab 21:15 keine Daten mehr aktualisiert. Am 23.05 um 15:20 hab ich dann den Adapter neu gestartet und er aktualisiert wieder.

<img width="1357" alt="Bildschirmfoto 2024-05-23 um 16 33 46" src="https://github.com/DrozmotiX/ioBroker.tado/assets/57620791/9e7a6137-f374-4491-b330-a7741064d3ee">

**Versions:**  
 - Adapter version: 0.54
 - JS-Controller version: 5.0.19
 - Node version: v18.20.3
 - Operating system:  Docker
 - 
**Additional context**

**Comment by HGlab01** [comment]
Hallo,
danke fürs Ticket!
Wenn ich dich richtig verstehe, dann gibt es keinen Eintrag im Log und trotzdem stoppt der Adapter die Datensammlung?
In der Tado-App werden weiterhin neue Temp.werte angezeigt? Was passiert, wenn du in dem Zustand über die Tado-App die Heizung ein oder ausschaltest? Ändert sich dann auch nichts im Adapter?

Ich fürchte dem Problem werden wir nur auf die Spur kommen (scheint ein echtes Einzelfallthema zu sein) wenn du den Adapter im Debug-Modus laufen lässt (auch wenn es viel Log erzeugen wird) solange bis das Verhalten auftritt und dann den Log des Adapters der letzten 10 Minuten zur Verfügung stellst.

Wenn keine Logs entstehen sieht es fast so aus, als würde sich der Prozess aufhängen Vielleicht kannst du auch mal mit
`top -o TIME+ -u iobroker`
checken, ob der Prozess noch CPU-Zeit konsumiert. Also ob TIME+ dann noch regelmäßig ansteigt

**Comment by serpentes80** [comment]
ich habe das gleiche Problem.
`top -c -p $(pgrep -d',' -f io.tado)`
TIME+ steigt nach wie vor, aber die Instanz ist tot

irgendwelche Ideen?
