### ISSUE TITLE
Rooms bleibt leer

### ISSUE THREAD

**Issue by 9Mad-Max5** [DrozmotiX/ioBroker.tado#845]
**Describe the bug**  
In der Objekt Struktur werden keine Rooms oder Räume angelegt auch wenn diese in Tado mittlerweile vorhanden sind.

**To Reproduce**  
1. Adapter hinzufügen
2. Anmeldedaten eingeben
3. Objekte anlegen lassen
4. Rooms bleibt eine leere liste /struct

**Expected behavior**  
Hier würde ich meine Tado Thermostat X in meinem zuvor angelegten Raum Flur erwarten

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 0.5.5
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: docker

**Comment by HGlab01** [comment]
Verwendest du die Produktserie "Tado X" und nicht Tado V3(+)/V2?
Wenn ja, dann unterstützt der Adapter Tado X nicht

**Comment by 9Mad-Max5** [comment]
Yes benutze einen Tado X also mit matter Unterstützung sah für mich auf den ersten Blick vergleichbar aus. Gibt es bereits ein Adapter der Tado X supportet.

**Comment by HGlab01** [comment]
Da kann ich dir leider nicht weiterhelfen - auch nicht warum sich Tado zu der Inkompatibilität entschieden hat...

**Comment by 9Mad-Max5** [comment]
Okidoki sehr interessant. Es sieht so aus, als würde alles bis auf die Räume gehen.

**Comment by HGlab01** [comment]
kannst mir mal einen Screenshot posten wie es aussieht?
und den Adapter im Debug-Modus starten und die Werte unter
`tado.0.xxxxx._JSON_response`
posten

Gerne auch per Mail oder Discord wenn dir das lieber ist

**Comment by HGlab01** [comment]
noch Interesse?

**Comment by 9Mad-Max5** [comment]
Ja ist aber leider von meiner Seite in Vergessenheit geraten und aktuell kämpfe ich gerade damit, den iobroker als container generell wieder ans Laufen zu bekommen.

**Comment by 9Mad-Max5** [comment]
![image](https://github.com/user-attachments/assets/06c4b9fc-4a0a-46a1-8f9a-f9432ef46e07)

Hier anbei ein Screenshot

**Comment by HGlab01** [comment]
sorry, aber auf dem Screenshot sehe ich nichts interessantes...

es gibt diese 5 Hauptfolder
![image](https://github.com/user-attachments/assets/7eb22521-1553-42bc-a731-4d8dae3f6af6)
welche davon haben Daten?
Unter _JSON_response steht im Screenshot nur NULL
War der Adapter im Debug-Modus?

**Comment by 9Mad-Max5** [comment]
Nein der Adapter war doch nicht im Debug-Mode.
Im _JSON_Response sind nun auch daten.
Generell sind in allen Ordern außer Rooms  sind Daten.
Also das Haus, die Mobilen Geräte und das Wetter sind angelegt.

**Comment by 9Mad-Max5** [comment]
Ich hatte gerade etwas Zeit und in der libtado nachgeschaut, dort scheint es auch noch nicht implementiert zu sein.
Hast du zufällig die Postman befehle gerade für die Authentifizierung, dann kann man den gesamt json dump leichter anschauen fürchte ich.

**Comment by HGlab01** [comment]
wie gesagt, bitte starte den Adapter im Debug-Modus und ermögliche mir den Zugriff auf die Daten unter `_JSON_response`
Das wäre der Start der Analyse

**Comment by 9Mad-Max5** [comment]
Welche form könnte parkikabel sein?
Hier die komplette response enthält mir evtl zu viele private informationen.
Sowas wie ein Discord call?

**Comment by HGlab01** [comment]
gerne per Discord --> hglab01

**Comment by ThatsIoT** [comment]
Ich stehe gerade vor der selben Herausforderung.
Die "JSON_response.Stage_08_ZonesData" bleiben einfach leer. Alles andere funktioniert.

**Comment by HGlab01** [comment]
first alpha version available
`iob upgrade tado@0.6.0-alpha.1`
