### ISSUE TITLE
support change of attribute light

### ISSUE THREAD

**Issue by denjo1982** [DrozmotiX/ioBroker.tado#861]
Hallo, ich habe mir die Klima Steuerung von Tado geholt und leider ist das objekt light schreibgeschützt?
Über die app kann ich das Steuern, kann man das ändern?

![image](https://github.com/user-attachments/assets/310c73fb-e30e-4c5c-9327-b33b186ca813)

**Comment by HGlab01** [comment]
Hallo! Was macht das Attribute?
Kannst du bitte mal den Adapter im Debug-Modus laufen lassen und dann zB horizontalSwing ändern und das gesamte Log sharen? Danke!

**Comment by denjo1982** [comment]
> Hallo! Was macht das Attribute? Kannst du bitte mal den Adapter im Debug-Modus laufen lassen und dann zB horizontalSwing ändern und das gesamte Log sharen? Danke!

Dadurch stellt man das Dislpay aus auf meiner Klimaanlage, zb in der Nacht wenn man schlafen will das leuchtet es nicht die ganze Nacht. Hab jetzt mal auf Debug gestellt und den Swing geändert.

`tado.0 | 2024-08-25 17:16:58.472 | debug | state tado.0.153091.Rooms.14.setting.verticalSwing changed: on (ack = false)
-- | -- | -- | --
tado.0 | 2024-08-25 17:16:58.472 | debug | State change detected from different source than adapter
tado.0 | 2024-08-25 17:16:58.472 | debug | checkExpire() done
tado.0 | 2024-08-25 17:16:58.319 | debug | state tado.0.153091.Rooms.14.setting.horizontalSwing changed: OFF (ack = true)
tado.0 | 2024-08-25 17:16:58.319 | debug | Changed value OFF for ID tado.0.153091.Rooms.14.setting.horizontalSwing stored
tado.0 | 2024-08-25 17:16:58.319 | debug | state tado.0.153091.Rooms.14.setting.verticalSwing changed: ON (ack = true)
tado.0 | 2024-08-25 17:16:58.319 | debug | Changed value ON for ID tado.0.153091.Rooms.14.setting.verticalSwing stored
tado.0 | 2024-08-25 17:16:58.319 | debug | state tado.0.153091.Rooms.14.setting.fanLevel changed: LEVEL1 (ack = true)
tado.0 | 2024-08-25 17:16:58.319 | debug | Changed value LEVEL1 for ID tado.0.153091.Rooms.14.setting.fanLevel stored
tado.0 | 2024-08-25 17:16:58.318 | debug | state tado.0.153091.Rooms.14.setting.temperature.fahrenheit changed: 69.8 (ack = true)
tado.0 | 2024-08-25 17:16:58.318 | debug | Changed value 69.8 for ID tado.0.153091.Rooms.14.setting.temperature.fahrenheit stored
tado.0 | 2024-08-25 17:16:58.318 | debug | state tado.0.153091.Rooms.14.setting.temperature.celsius changed: 21 (ack = true)
tado.0 | 2024-08-25 17:16:58.318 | debug | Changed value 21 for ID tado.0.153091.Rooms.14.setting.temperature.celsius stored
tado.0 | 2024-08-25 17:16:58.318 | debug | state tado.0.153091.Rooms.14.setting.mode changed: COOL (ack = true)
tado.0 | 2024-08-25 17:16:58.318 | debug | Changed value COOL for ID tado.0.153091.Rooms.14.setting.mode stored
tado.0 | 2024-08-25 17:16:58.318 | debug | state tado.0.153091.Rooms.14.setting.power changed: ON (ack = true)
tado.0 | 2024-08-25 17:16:58.318 | debug | Changed value ON for ID tado.0.153091.Rooms.14.setting.power stored
tado.0 | 2024-08-25 17:16:58.318 | debug | state tado.0.153091.Rooms.14.overlay.termination.typeSkillBasedApp changed: MANUAL (ack = true)
tado.0 | 2024-08-25 17:16:58.318 | debug | Changed value MANUAL for ID tado.0.153091.Rooms.14.overlay.termination.typeSkillBasedApp stored
tado.0 | 2024-08-25 17:16:58.285 | debug | state tado.0.153091.Rooms.14.overlay.setting.horizontalSwing changed: OFF (ack = true)
tado.0 | 2024-08-25 17:16:58.285 | debug | Changed value OFF for ID tado.0.153091.Rooms.14.overlay.setting.horizontalSwing stored
tado.0 | 2024-08-25 17:16:58.283 | debug | state tado.0.153091.Rooms.14.overlay.setting.verticalSwing changed: ON (ack = true)
tado.0 | 2024-08-25 17:16:58.283 | debug | Changed value ON for ID tado.0.153091.Rooms.14.overlay.setting.verticalSwing stored
tado.0 | 2024-08-25 17:16:58.282 | debug | state tado.0.153091.Rooms.14.overlay.setting.fanLevel changed: LEVEL1 (ack = true)
tado.0 | 2024-08-25 17:16:58.281 | debug | Changed value LEVEL1 for ID tado.0.153091.Rooms.14.overlay.setting.fanLevel stored
tado.0 | 2024-08-25 17:16:58.280 | debug | state tado.0.153091.Rooms.14.overlay.setting.temperature.fahrenheit changed: 69.8 (ack = true)
tado.0 | 2024-08-25 17:16:58.280 | debug | Changed value 69.8 for ID tado.0.153091.Rooms.14.overlay.setting.temperature.fahrenheit stored
tado.0 | 2024-08-25 17:16:58.279 | debug | state tado.0.153091.Rooms.14.overlay.setting.temperature.celsius changed: 21 (ack = true)
tado.0 | 2024-08-25 17:16:58.279 | debug | Changed value 21 for ID tado.0.153091.Rooms.14.overlay.setting.temperature.celsius stored
tado.0 | 2024-08-25 17:16:58.278 | debug | state tado.0.153091.Rooms.14.overlay.setting.mode changed: COOL (ack = true)
tado.0 | 2024-08-25 17:16:58.278 | debug | Changed value COOL for ID tado.0.153091.Rooms.14.overlay.setting.mode stored
tado.0 | 2024-08-25 17:16:58.277 | debug | state tado.0.153091.Rooms.14.overlay.setting.power changed: ON (ack = true)
tado.0 | 2024-08-25 17:16:58.277 | debug | Changed value ON for ID tado.0.153091.Rooms.14.overlay.setting.power stored
tado.0 | 2024-08-25 17:16:58.252 | debug | checkExpire() searchpattern is 153091.Rooms.14.overlay.*
tado.0 | 2024-08-25 17:16:58.251 | debug | CheckExpire() at setZoneOverlay() started
tado.0 | 2024-08-25 17:16:58.238 | debug | API called with {"setting":{"type":"AIR_CONDITIONING","power":"ON","mode":"COOL","temperature":{"celsius":21},"horizontalSwing":"OFF","verticalSwing":"ON","fanLevel":"LEVEL1","light":"OFF"},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
tado.0 | 2024-08-25 17:16:58.238 | debug | API 'ZoneOverlay' for home '153091' and zone '14' with body {"setting":{"type":"AIR_CONDITIONING","power":"ON","mode":"COOL","temperature":{"celsius":21},"horizontalSwing":"OFF","verticalSwing":"ON","fanLevel":"LEVEL1","light":"OFF"},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}} called.
tado.0 | 2024-08-25 17:16:58.238 | debug | API request finalized for '153091/14'
tado.0 | 2024-08-25 17:16:58.088 | debug | Body "{"setting":{"type":"AIR_CONDITIONING","power":"ON","mode":"COOL","temperature":{"celsius":21},"horizontalSwing":"OFF","verticalSwing":"ON","fanLevel":"LEVEL1","light":"OFF"},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}" for API call "/api/v2/homes/153091/zones/14/overlay"
tado.0 | 2024-08-25 17:16:58.087 | debug | 750ms queuing done [timer:'15309114']. API will be caled.
tado.0 | 2024-08-25 17:16:57.308 | debug | poolApiCall() entered for '153091/14'
tado.0 | 2024-08-25 17:16:57.308 | debug | verticalSwing changed for room '14' in home '153091' to 'ON'
tado.0 | 2024-08-25 17:16:57.308 | debug | Light is: OFF
tado.0 | 2024-08-25 17:16:57.308 | debug | Swing is: NOT_AVAILABLE
tado.0 | 2024-08-25 17:16:57.308 | debug | VerticalSwing is: ON
tado.0 | 2024-08-25 17:16:57.308 | debug | HorizontalSwing is: OFF
tado.0 | 2024-08-25 17:16:57.308 | debug | FanLevel is: LEVEL1
tado.0 | 2024-08-25 17:16:57.308 | debug | FanSpeed is: NOT_AVAILABLE
tado.0 | 2024-08-25 17:16:57.308 | debug | Mode is: COOL
tado.0 | 2024-08-25 17:16:57.308 | debug | NextTimeBlockStart exists: true
tado.0 | 2024-08-25 17:16:57.308 | debug | DurationInSeconds is: 1800
tado.0 | 2024-08-25 17:16:57.308 | debug | Execution mode (typeSkillBasedApp) is: MANUAL
tado.0 | 2024-08-25 17:16:57.308 | debug | Temperature is: 21
tado.0 | 2024-08-25 17:16:57.308 | debug | Power is: ON
tado.0 | 2024-08-25 17:16:57.308 | debug | Type is: AIR_CONDITIONING
tado.0 | 2024-08-25 17:16:57.287 | debug | Attribute 'tado.0.153091.Rooms.14.setting.verticalSwing' changed. 'verticalSwing' will be checked.
tado.0 | 2024-08-25 17:16:57.286 | debug | GETS INTERESSTING!!!`

**Comment by HGlab01** [comment]
kannst die Version
`DrozmotiX/ioBroker.tado#88493f23d8c3ac7217c93542eba85d47cf564817`
probieren
über
![image](https://github.com/user-attachments/assets/007c775b-308e-40f8-979c-0861403a502c)
und 
![image](https://github.com/user-attachments/assets/3170c0e8-b79d-4b93-84fb-495e886aba5b)

**Comment by denjo1982** [comment]
ist das eine neue tado version? Der Datenpunkt ist immer noch schreibgeschützt.

**Comment by HGlab01** [comment]
any news?
