### ISSUE TITLE
Please add support for Tado X devices

### ISSUE THREAD

**Issue by ThatsIoT** [DrozmotiX/ioBroker.tado#895]
First of all, thank you for your work so far. 
Is it possible to provide support for TADO X? I would like to support development.

Thank you very much

Open tasks for first alpha version
- [x] support modes Auto / Manual / Timer
- [x] support boost and back from boost
- [x] support all on and all off
- [x] refactorings
- [x] add attributes to lib
- [x] add infos to readme (support and states which can be changed)

**Comment by HGlab01** [comment]
Hi,
I started first research work and it is a lot different and therefore a lot to day.
What I would need is an account with TadoX device(s) and in a later step some testers.

If you have Discord (HGlab01) we can talk there how you can support best.

**Comment by HGlab01** [comment]
great! My user is
HGlab01

**Comment by HGlab01** [comment]
Open tasks for first alpha version
- [ ] support modes Auto / Manual / Timer
- [ ] support boost and back from boost
- [ ] support all on and all off
- [ ] refactorings

**Comment by ThatsIoT** [comment]
Thanks for the great work. It works perfectly :-)

**Comment by HGlab01** [comment]
I will launch a first alpha version today or tomorrow.
After installing the alpha version it's recommended to delete all states and restart the adapter.

**Comment by HGlab01** [comment]
first alpha version available
`iob upgrade tado@0.6.0-alpha.1`
