### ISSUE TITLE
Tado X Adapter - no registration in Cloud

### ISSUE THREAD

**Issue by BorstiUser** [DrozmotiX/ioBroker.tado#921]
Hello,

Is there an approach for me to use the Tado adapter in conjunction with the Tado gateway (firmware 239.1) and thermostat (firmware 243.1) in IOBroker  

PlatformOperating system:linux
Architecture: arm64
CPUs:4
Speed: 1800MHz
Model: Cortex-A72
RAM:3.7GB
System uptime: 6 d. 20:11:32
Node.js:v20.18.1
time:1732870623214
timeOffset:-60
NPM:10.8.2
Number of adapters: 547
Disk size: 116.9 GB
Free disk space: 102.3 GB
Active instances:19
Path:/opt/iobroker/
Operating time:23:38:02
active:true
_nodeCurrent:20.18.1
_nodeNewest:20.18.1
_nodeNewestNext:20.18.1
_npmCurrent:10.8.2
_npmNewest:10.8.2
_npmNewestNext:10.8.2

to get it working with AdapterVersion 0.6.1? 

App works on Android, adapter comes with error:

tado.0
	2024-11-29 09:57:29.219 error Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0
	2024-11-29 09:57:29.217 error Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0
	2024-11-29 09:57:29.191 error Error: Error: Response Error: 400
tado.0
	2024-11-29 09:57:28.541 info Started with JSON Explorer version 0.1.16
tado.0
	2024-11-29 09:57:28.506 info starting. Version 0.6.1 in /opt/iobroker/node_modules/iobroker.tado, node: v20.18.1, js-controller: 7.0.3
host.raspberrypi
	2024-11-29 09:57:24.201 info instance system.adapter.tado.0 in version "0.6.1" started with pid 1564555
host.raspberrypi
	2024-11-29 09:57:22.982 info "system.adapter.tado.0" enabled

rejected.

Login password has already been changed, no special characters.

greetings

Borsti

**Comment by HGlab01** [comment]
The adapter is only working with the Tado Cloud Server

**Comment by HGlab01** [comment]
my fault! I missunderstood "no registration in Cloud" in the title...
I just checked the code and the 400 issue says that username and or pw are not correct.
I changed my PW to a mismatched one and got the same three error lines
```
tado.0 | 2024-11-29 10:58:06.181 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2024-11-29 10:58:06.180 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2024-11-29 10:58:06.162 | error | Error: Error: Response Error: 400
```
I know you checked user and pw, but can you please recheck it again. Maybe with the copy&paste a "blank" or what ever was copied as well?

If it is not working at all please switch the adapter to debug mode and let's see what the log provides.

**Comment by BorstiUser** [comment]
tado.0 | 2024-11-29 11:11:22.445 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
-- | -- | -- | --
tado.0 | 2024-11-29 11:11:22.444 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2024-11-29 11:11:22.441 | error | Error: Error: Response Error: 400
tado.0 | 2024-11-29 11:11:22.148 | debug | ConnState   {"val":false,"ack":true,"ts":1732875052117,"q":0,"from":"system.adapter.tado.0","user":"system.user.admin","lc":1732705317308}
tado.0 | 2024-11-29 11:11:22.135 | debug | Internet connection detected. Everything fine!
tado.0 | 2024-11-29 11:10:52.100 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2024-11-29 11:10:52.099 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2024-11-29 11:10:52.093 | error | Error: Error: Response Error: 400
tado.0 | 2024-11-29 11:10:51.820 | debug | ConnState   {"val":false,"ack":true,"ts":1732875021790,"q":0,"from":"system.adapter.tado.0","user":"system.user.admin","lc":1732705317308}
tado.0 | 2024-11-29 11:10:51.814 | debug | Internet connection detected. Everything fine!
tado.0 | 2024-11-29 11:10:21.778 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2024-11-29 11:10:21.777 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2024-11-29 11:10:21.770 | error | Error: Error: Response Error: 400
tado.0 | 2024-11-29 11:10:21.471 | debug | ConnState   {"val":false,"ack":true,"ts":1732874992088,"q":0,"from":"system.adapter.tado.0","user":"system.user.admin","lc":1732705317308}
tado.0 | 2024-11-29 11:10:21.464 | debug | Internet connection detected. Everything fine!
tado.0 | 2024-11-29 11:09:51.430 | error | Disconnected from Tado cloud service ..., retry in 30 seconds !
tado.0 | 2024-11-29 11:09:51.428 | error | Error in data refresh at step login: Error: Login failed! Please verify Username and Password
tado.0 | 2024-11-29 11:09:51.391 | error | Error: Error: Response Error: 400
tado.0 | 2024-11-29 11:09:51.015 | debug | ConnState   {"val":false,"ack":true,"ts":1732874990029,"q":0,"from":"system.adapter.tado.0","user":"system.user.admin","lc":1732705317308}
tado.0 | 2024-11-29 11:09:50.277 | debug | Internet connection detected. Everything fine!
tado.0 | 2024-11-29 11:09:49.900 | info | Started with JSON-Explorer version 0.1.16
tado.0 | 2024-11-29 11:09:49.868 | info | starting. Version 0.6.1 in /opt/iobroker/node_modules/iobroker.tado, node: v20.18.1, js-controller: 7.0.3
tado.0 | 2024-11-29 11:09:49.232 | debug | Plugin sentry Initialize Plugin (enabled=true)
tado.0 | 2024-11-29 11:09:48.908 | debug | States create User PubSub Client
tado.0 | 2024-11-29 11:09:48.905 | debug | States create System PubSub Client
tado.0 | 2024-11-29 11:09:48.792 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
tado.0 | 2024-11-29 11:09:48.665 | debug | Objects connected to redis: 127.0.0.1:9001
tado.0 | 2024-11-29 11:09:48.651 | debug | Objects client initialize lua scripts
tado.0 | 2024-11-29 11:09:48.269 | debug | Objects create User PubSub Client

**Comment by BorstiUser** [comment]
User and PW are not copied - wrote "digit by digit"

i know such errors... It's definitely an overlooked problem ;o(

**Comment by HGlab01** [comment]
would it be an option, that you add my user to your installation to see if it works? if you like we can switch to discord for easier communication

**Comment by BorstiUser** [comment]
discord isn´t an option

but you can give me any Login Option to another tado system - thats right

**Comment by BorstiUser** [comment]
i can test it tommorow - or later

**Comment by HGlab01** [comment]
if you like you can add this account to your installation
zsw33670@inohm.com
and I can test it - that's the only option I can provide

**Comment by BorstiUser** [comment]
very strange - i have added another User to Tado app with an other eMail and PW

it works

is there any restriction? i have also special characters

The non-working email is at outlook.com

very special

**Comment by HGlab01** [comment]
not that I am aware as the adapter just hands over the credentials to Tado server and if it works in the app then it should work in the adapter as well

**Comment by BorstiUser** [comment]
Thanks for thinking quickly and have a nice weekend
